#include <catch2/catch.hpp>

#include "libslic3r/AceMmuRewrite.hpp"

#include <boost/filesystem.hpp>
#include <boost/nowide/fstream.hpp>

#include <cstdlib>
#include <sstream>
#include <string>
#include <vector>

using namespace Slic3r;
using namespace Slic3r::AceMmu;

// A logical file in the stock U1 template's shape: the start gcode with its two selections of
// the initial tool and the prime line, the layer -1 marker, then one block per tool change the
// way `change_filament_gcode` and OozePrevention write them.
namespace {

std::string start_gcode(int init)
{
    std::string s;
    s += "; HEADER_BLOCK_START\n; generated by Snapmaker Orca\n; HEADER_BLOCK_END\n\n";
    s += "; EXECUTABLE_BLOCK_START\n";
    s += ";===== date: 20260128 =====================\n\nPRINT_START\n";
    s += "M104 T" + std::to_string(init) + " S140\n";
    s += "G28 X Y\n;===== bed check ========\nT" + std::to_string(init) + "\nG90\n";
    s += "SM_PRINT_EXTRUDER_PREHEAT EXTRUDER=1 TEMP=140\nSM_PRINT_AUTO_FEED EXTRUDER=0\n";
    s += "M104 S0 T0 A0\nM104 S0 T1 A0\nM104 S0 T2 A0\nM104 S0 T3 A0\n";
    s += "M104 T" + std::to_string(init) + " S130\n\n;===== homing =================\nT" + std::to_string(init) + "\n";
    s += "M109 T" + std::to_string(init) + " S130\nG28 Z\n\n";
    s += ";===== \xe7\x94\xbb\xe8\xb5\xb7\xe5\xa7\x8b\xe7\xba\xbf =================\n";
    s += "G90\nG1 Z1.5\nG0 X85 Y1 Z2 F18000\nM109 S220\nG1 Z0.2\nM83\nG1 X185 E15 F360\nG1 Z1.5\n\nG90\nM106 S0\n";
    s += "G21\nM83 ; use relative distances for extrusion\n";
    s += ";===== date: 20251213=====================\n";
    s += "; Change Tool" + std::to_string(init) + " -> Tool" + std::to_string(init) + " (layer -1)\n";
    s += "G91\nG1 Z1.5 F1800\nG90\nG1 F21000\nM400\nT" + std::to_string(init) + "\nG90\n";
    s += ";LAYER_CHANGE\n;Z:0.25\nG1 X10 Y10 F3000\nG1 X20 Y10 E0.5\n";
    return s;
}

std::string change(int prev, int next, int layer, bool preextrude = true)
{
    std::string s;
    s += "M104 S70 T" + std::to_string(prev) + " ; set nozzle temperature ;cooldown\n";
    s += ";===== date: 20251213=====================\n";
    s += "; Change Tool" + std::to_string(prev) + " -> Tool" + std::to_string(next) + " (layer " + std::to_string(layer) + ")\n";
    s += "G91\nG1 Z1.5 F1800\nG90\nG1 F21000\n\n; " + std::to_string(layer) + "\n";
    s += "M109 S220 T" + std::to_string(next) + "\nM400\nT" + std::to_string(next) + "\n";
    if (preextrude)
        s += "SM_PRINT_PREEXTRUDE_FILAMENT INDEX=" + std::to_string(next) + "\n";
    s += "G90\nM104 S220 T" + std::to_string(next) + " ; set nozzle temperature\n";
    s += "G1 X20 Y20 E0.5\nG1 X30 Y20 E0.5\n";
    return s;
}

std::string end_gcode()
{
    return "M104 S0\nM140 S0\n; EXECUTABLE_BLOCK_END\n\n; CONFIG_BLOCK_START\n; flush_multiplier = 1\n; CONFIG_BLOCK_END\n";
}

// The U1 as the reference machine has it: three stock feeders and one four-bay ACE on head 4.
RewriteInput u1_topology(int filaments)
{
    RewriteInput in;
    in.mode          = "head";
    in.head_unit     = {-1, -1, -1, 0};
    in.head_capacity = {1, 1, 1, 4};
    static const char* colours[] = {"#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff", "#00ffff", "#000000", "#ffffff"};
    for (int i = 0; i < filaments; ++i) {
        RewriteFilament f;
        f.colour = colours[i % 8];
        f.type   = "PLA";
        in.filaments.push_back(f);
    }
    return in;
}

std::vector<std::string> lines_of(const std::string& s)
{
    std::vector<std::string> out;
    std::istringstream       is(s);
    std::string              l;
    while (std::getline(is, l))
        out.push_back(l);
    return out;
}

// With ACE_REWRITE_KEEP_DIR set, a case's input and output are kept as files, for
// docs/u1-webui/tools/ace_rewrite_diff.py to run multiACE's own rewriter over.
void keep_pair(const std::string& name, const std::string& logical, const std::string& sibling)
{
    const char* dir = std::getenv("ACE_REWRITE_KEEP_DIR");
    if (dir == nullptr || *dir == '\0')
        return;
    boost::filesystem::create_directories(dir);
    boost::nowide::ofstream a((boost::filesystem::path(dir) / (name + ".logical.gcode")).string(), std::ios::binary);
    a << logical;
    boost::nowide::ofstream b((boost::filesystem::path(dir) / (name + ".ace.gcode")).string(), std::ios::binary);
    b << sibling;
}

int count_prefix(const std::vector<std::string>& lines, const std::string& pfx)
{
    int n = 0;
    for (const auto& l : lines)
        if (l.compare(0, pfx.size(), pfx) == 0)
            ++n;
    return n;
}

int index_of(const std::vector<std::string>& lines, const std::string& exact, int from = 0)
{
    for (int i = from; i < int(lines.size()); ++i)
        if (lines[i] == exact)
            return i;
    return -1;
}

int index_containing(const std::vector<std::string>& lines, const std::string& part, int from = 0)
{
    for (int i = from; i < int(lines.size()); ++i)
        if (lines[i].find(part) != std::string::npos)
            return i;
    return -1;
}

} // namespace

TEST_CASE("pass A reads the initial tool, the body sequence and the anchor", "[ace_mmu_rewrite]")
{
    std::string g = start_gcode(1) + change(1, 4, 0) + change(4, 2, 0) + change(2, 1, 1) + change(1, 5, 1) + end_gcode();
    std::istringstream in(g);
    ToolSequence       seq = scan_tool_sequence(in);
    CHECK(seq.initial == 1);
    CHECK(seq.body == std::vector<int>{1, 4, 2, 1, 5});
    CHECK(seq.used == std::vector<int>{1, 2, 4, 5});
    CHECK(seq.max_tool == 5);
    const auto lines = lines_of(g);
    CHECK(seq.first_marker == index_of(lines, "; Change Tool1 -> Tool1 (layer -1)"));
    CHECK(seq.first_extruding == index_of(lines, "G1 X185 E15 F360"));
    // The boundary right before the prime line is the prime section's own header.
    CHECK(seq.anchor == index_containing(lines, "\xe7\x94\xbb\xe8\xb5\xb7\xe5\xa7\x8b\xe7\xba\xbf"));
    CHECK(seq.anchor < seq.first_extruding);
    CHECK(seq.anchor < seq.first_marker);
}

TEST_CASE("an ordinary plate on stock feeders is left exactly as it is", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(3);
    std::string  g  = start_gcode(0) + change(0, 1, 0) + change(1, 2, 0) + change(2, 0, 1) + end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    CHECK_FALSE(r.rewritten);
    CHECK(os.str().empty());
    REQUIRE(r.plan.feasible);
    CHECK(r.plan.swaps == 0);
    CHECK(r.plan.head_of == std::vector<int>{0, 1, 2});
}

TEST_CASE("normal mode never rewrites", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(2);
    in.mode         = "normal";
    std::istringstream is(start_gcode(0) + change(0, 1, 0) + end_gcode());
    std::ostringstream os;
    CHECK_FALSE(rewrite_gcode(is, os, in).rewritten);
    CHECK(os.str().empty());
}

TEST_CASE("a two-filament plate forced onto the ACE head, line by line", "[ace_mmu_rewrite]")
{
    // Both filaments on head 4 (index 3), so every change is a bay swap and the output is
    // fully determined: this pins the exact emission format.
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};
    in.flush_matrix  = {0.f, 100.f, 120.f, 0.f}; // mm3, [from * 2 + to]
    std::string g    = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    CHECK(r.plan.head_of == std::vector<int>{3, 3});
    CHECK(r.plan.slot_of == std::vector<int>{1, 0}); // first-use order: filament 1 first
    CHECK(r.swaps == 2);
    CHECK(r.plan.swaps == 2);
    CHECK(r.preload_slot == std::vector<int>{-1, -1, -1, 0});
    CHECK(r.runs[3] == std::vector<int>{1, 0});

    const auto out = lines_of(os.str());
    const auto src = lines_of(g);
    CHECK(out.size() == src.size() + 6 /* block */ + 2 * 3 /* two swaps: comment, stamp, swap */ - 2 /* both pre-extrudes dropped */);

    // The start gcode: only the initial tool's references move, the physical shutdowns stay.
    CHECK(index_of(out, "M104 T3 S140") >= 0);
    CHECK(index_of(out, "M104 T1 S140") < 0);
    CHECK(index_of(out, "M104 S0 T1 A0") >= 0);
    CHECK(index_of(out, "M104 S0 T3 A0") >= 0);
    CHECK(index_of(out, "M104 T3 S130") >= 0);
    CHECK(index_of(out, "M109 T3 S130") >= 0);
    CHECK(index_of(out, "M109 S220") >= 0);
    CHECK(count_prefix(out, "T1") == 0);
    CHECK(count_prefix(out, "T3") == 5); // two start-gcode selections + layer -1 + two changes

    // The preload block sits right before the prime section's header.
    const int hdr = index_of(out, "; multiACE plan: T0:H3S1 T1:H3S0 swaps:2 optimal:0");
    REQUIRE(hdr >= 0);
    CHECK(out[hdr + 1] == "; multiACE auto-load: load 1 head(s)");
    CHECK(out[hdr + 2] == "; multiACE processed: format=4");
    CHECK(out[hdr + 3] == "ACE_SET_PURGE RESET=1");
    CHECK(out[hdr + 4] == "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=0 INITIAL=1");
    CHECK(out[hdr + 5] == "; multiACE auto-load: end");
    CHECK(out[hdr + 6].find("\xe7\x94\xbb\xe8\xb5\xb7\xe5\xa7\x8b\xe7\xba\xbf") != std::string::npos);

    // The layer -1 selection of the preloaded filament is a bare T3 and nothing else.
    const int m1 = index_of(out, "; Change Tool1 -> Tool1 (layer -1)");
    REQUIRE(m1 >= 0);
    const int t1 = index_of(out, "T3", m1);
    CHECK(out[t1 + 1] == "G90");

    // The first change: 1 -> 0 on the same head is a swap with the slicer's pair length.
    const int c0 = index_of(out, "; Change Tool1 -> Tool0 (layer 0)");
    REQUIRE(c0 >= 0);
    CHECK(out[c0 - 2] == "M104 S70 T3 ; set nozzle temperature ;cooldown");
    CHECK(index_of(out, "M109 S220 T3", c0) == c0 + 7);
    const int t0 = index_of(out, "T3", c0);
    CHECK(out[t0 + 1] == "; multiACE: head 3 must present ACE 0 slot 1");
    CHECK(out[t0 + 2] == "ACE_SET_PURGE LENGTH=" + format_length(purge_length_mm(in, 1, 0)));
    CHECK(out[t0 + 3] == "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=1");
    // The pre-extrude after a swap is dropped (the swap flushes); the head was primed by the
    // start gcode.
    CHECK(out[t0 + 4] == "G90");
    CHECK(out[t0 + 5] == "M104 S220 T3 ; set nozzle temperature");

    const double mm10 = purge_length_mm(in, 1, 0);
    CHECK(mm10 == Approx(120. / (3.14159265358979 * 0.25 * 1.75 * 1.75)));
    CHECK(format_length(mm10) == "49.89");
    CHECK(format_length(purge_length_mm(in, 0, 1)) == "41.575");
    CHECK(r.stamped == 2);
    CHECK(r.purge_mm == Approx(mm10 + purge_length_mm(in, 0, 1)));
    CHECK(r.purge_g == Approx((120. + 100.) * 1.24 / 1000.));
    CHECK(r.preflight_purge_mm == Approx(40. + 40.)); // both under the 40 mm floor
    CHECK(count_prefix(out, "SM_PRINT_PREEXTRUDE_FILAMENT") == 0);
    CHECK(r.dropped_standbys == 0);
    CHECK(r.header_line == out[hdr]);
    keep_pair("two-on-ace", g, os.str());
}

TEST_CASE("seven filaments over three feeders and a four-bay head", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(7);
    in.flush_matrix.assign(49, 140.f);
    for (int i = 0; i < 7; ++i)
        in.flush_matrix[i * 7 + i] = 0.f;

    // Two busy colours that alternate, five rare ones - the shape the planner is for.
    std::string g = start_gcode(0);
    int         prev = 0;
    const int   seq[] = {1, 0, 1, 2, 0, 1, 3, 0, 1, 4, 0, 1, 5, 0, 1, 6, 0, 1, 2, 3, 0, 1, 4, 5, 6, 0};
    int         layer = 0;
    for (int t : seq) {
        g += change(prev, t, layer++);
        prev = t;
    }
    g += end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    REQUIRE(r.plan.feasible);
    CHECK(r.plan.optimal);
    const auto out = lines_of(os.str());

    // Every selection names a physical head and no tool the printer lacks.
    for (const auto& l : out) {
        if (l.size() >= 2 && l[0] == 'T' && isdigit((unsigned char) l[1]))
            CHECK(l.size() == 2);
        if (l.rfind("M109 S220 T", 0) == 0 || l.rfind("M104 S220 T", 0) == 0 || l.rfind("M104 S70 T", 0) == 0)
            CHECK(l[l.find(" T") + 2] <= '3');
    }
    CHECK(count_prefix(out, "T4") + count_prefix(out, "T5") + count_prefix(out, "T6") == 0);
    // The emitted swaps agree with the planner's count, and each one carries its stamp.
    CHECK(r.swaps == r.plan.swaps);
    CHECK(count_prefix(out, "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=") == r.swaps + 1); // + the preload
    CHECK(count_prefix(out, "ACE_SET_PURGE LENGTH=") == r.swaps);
    CHECK(r.stamped == r.swaps);
    CHECK(r.purge_mm == Approx(r.swaps * 140. / (3.14159265358979 * 0.25 * 1.75 * 1.75)));
    // Four filaments live on the ACE head, three on the feeders, and the busy pair never swaps.
    int on_ace = 0;
    for (int h : r.plan.head_of)
        on_ace += (h == 3);
    CHECK(on_ace == 4);
    CHECK(r.plan.head_of[0] != 3);
    CHECK(r.plan.head_of[1] != 3);
    CHECK(r.runs[3].size() == 4);
    // The header parses back to the same layout.
    LoadingPlan back;
    REQUIRE(parse_plan_header(r.header_line, back));
    CHECK(back.head_of == r.plan.head_of);
    CHECK(back.slot_of == r.plan.slot_of);
    CHECK(back.swaps == r.plan.swaps);
    CHECK(back.optimal == r.plan.optimal);
    // The feeders keep their pre-extrude at every change; the ACE head primes once at most.
    int ace_primes = 0, feeder_primes = 0;
    for (const auto& l : out)
        if (l.rfind("SM_PRINT_PREEXTRUDE_FILAMENT INDEX=", 0) == 0)
            (l.back() == '3' ? ace_primes : feeder_primes)++;
    CHECK(ace_primes <= 1);
    CHECK(feeder_primes > 0);
    CHECK(r.dropped_standbys == 0); // every cooldown here is followed by the M109 that re-heats
    keep_pair("seven", g, os.str());
}

TEST_CASE("a standby that would cool the printing head is dropped, and no other is", "[ace_mmu_rewrite]")
{
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};
    // Print-by-object shape: after the change to tool 0 the slicer parks the OTHER tool - which
    // shares the head - and prints on it at 70 C. That line, and only that line, goes.
    std::string g = start_gcode(1) + change(1, 0, 0);
    g += "M104 S70 T1 ; set nozzle temperature ;cooldown\n";
    g += "G1 X40 Y20 E0.5\n";
    g += change(0, 1, 1);
    g += end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    CHECK(r.dropped_standbys == 1);
    const auto out = lines_of(os.str());
    const int  c0  = index_of(out, "; Change Tool1 -> Tool0 (layer 0)");
    REQUIRE(c0 >= 0);
    // The cooldown before the change survives: the M109 six lines later re-heats the head.
    CHECK(out[c0 - 2] == "M104 S70 T3 ; set nozzle temperature ;cooldown");
    const int dropped = index_containing(out, "; multiACE dropped: M104 S70 T3 ; set nozzle temperature ;cooldown", c0);
    REQUIRE(dropped >= 0);
    CHECK(out[dropped].find("would cool the printing head below 170 C") != std::string::npos);
    CHECK(out[dropped + 1] == "G1 X40 Y20 E0.5");
    // And the change back to tool 1 keeps its own cooldown, which its M109 answers.
    const int c1 = index_of(out, "; Change Tool0 -> Tool1 (layer 1)");
    REQUIRE(c1 >= 0);
    CHECK(out[c1 - 2] == "M104 S70 T3 ; set nozzle temperature ;cooldown");
    keep_pair("standby", g, os.str());
}

TEST_CASE("more filaments than places is refused with the counts", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(8);
    std::string  g  = start_gcode(0);
    int          prev = 0;
    for (int t = 1; t < 8; ++t) {
        g += change(prev, t, t);
        prev = t;
    }
    g += change(7, 0, 8) + end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    REQUIRE_THROWS_AS(rewrite_gcode(is, os, in), RewriteRefusal);
    std::istringstream is2(g);
    try {
        rewrite_gcode(is2, os, in);
    } catch (const RewriteRefusal& e) {
        const std::string m = e.what();
        CHECK(m.find("8 filaments") != std::string::npos);
        CHECK(m.find("7 places") != std::string::npos);
        CHECK(m.find("3 stock feeder(s)") != std::string::npos);
        CHECK(m.find("4 ACE slot(s)") != std::string::npos);
        CHECK(m.find("Cheapest to drop") != std::string::npos);
    }
    CHECK(os.str().empty());
}

TEST_CASE("a tool the project has no filament for is refused", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(4);
    std::istringstream is(start_gcode(0) + change(0, 5, 0) + end_gcode());
    std::ostringstream os;
    REQUIRE_THROWS_WITH(rewrite_gcode(is, os, in), Catch::Contains("T5") && Catch::Contains("4 filament"));
}

TEST_CASE("combined mode and a shared unit are refused for now", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(2);
    in.mode         = "multi";
    REQUIRE_THROWS_WITH(plan_heads(in), Catch::Contains("Combined"));
    in.mode          = "head";
    in.head_unit     = {-1, -1, 0, 0};
    in.head_capacity = {1, 1, 4, 4};
    REQUIRE_THROWS_WITH(plan_heads(in), Catch::Contains("share ACE 1"));
    in.head_unit     = {-1, -1, -1, -1};
    in.head_capacity = {1, 1, 1, 4};
    REQUIRE_THROWS_WITH(plan_heads(in), Catch::Contains("no ACE unit"));
}

TEST_CASE("the plan header round-trips", "[ace_mmu_rewrite]")
{
    LoadingPlan p;
    p.feasible = true;
    p.optimal  = true;
    p.swaps    = 300;
    p.head_of  = {3, 3, 0, 1, 2, 3, 3, -1};
    p.slot_of  = {3, 0, 0, 0, 0, 2, 1, -1};
    const std::string line = plan_header_line(p);
    CHECK(line == "; multiACE plan: T0:H3S3 T1:H3S0 T2:H0S0 T3:H1S0 T4:H2S0 T5:H3S2 T6:H3S1 swaps:300 optimal:1");
    LoadingPlan back;
    REQUIRE(parse_plan_header(line, back));
    CHECK(back.head_of == std::vector<int>{3, 3, 0, 1, 2, 3, 3});
    CHECK(back.slot_of == std::vector<int>{3, 0, 0, 0, 0, 2, 1});
    CHECK(back.swaps == 300);
    CHECK(back.optimal);
    CHECK(back.feasible);
    CHECK_FALSE(parse_plan_header("; multiACE plan: {\"json\": 1}", back));
    CHECK_FALSE(parse_plan_header("; something else", back));
}

TEST_CASE("format_length is three decimals, trimmed, locale-free", "[ace_mmu_rewrite]")
{
    CHECK(format_length(47.271) == "47.271");
    CHECK(format_length(47.2704) == "47.27");
    CHECK(format_length(80.) == "80");
    CHECK(format_length(0.0004) == "0");
    CHECK(format_length(-1.) == "0");
}

TEST_CASE("rewrite_file writes the sibling only when there is something to write", "[ace_mmu_rewrite]")
{
    namespace fs = boost::filesystem;
    const fs::path dir = fs::temp_directory_path() / fs::unique_path("ace-rewrite-%%%%-%%%%");
    fs::create_directories(dir);
    const std::string in_path  = (dir / "plate.gcode").string();
    const std::string out_path = (dir / "plate.ace.gcode").string();

    // An ordinary plate: no sibling appears.
    {
        boost::nowide::ofstream f(in_path, std::ios::binary);
        f << start_gcode(0) << change(0, 1, 0) << change(1, 2, 0) << end_gcode();
    }
    RewriteResult r = rewrite_file(in_path, out_path, u1_topology(3));
    CHECK_FALSE(r.rewritten);
    CHECK_FALSE(fs::exists(out_path));

    // An ACE plate: the sibling is the rewritten file and the original is untouched.
    const std::string logical = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();
    {
        boost::nowide::ofstream f(in_path, std::ios::binary);
        f << logical;
    }
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};
    int ticks        = 0;
    r                = rewrite_file(in_path, out_path, in, [&ticks]() { ++ticks; });
    REQUIRE(r.rewritten);
    CHECK(r.swaps == 2);
    CHECK(ticks >= 2);
    REQUIRE(fs::exists(out_path));
    std::string back, orig;
    {
        boost::nowide::ifstream f(out_path, std::ios::binary);
        back.assign(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
        boost::nowide::ifstream g(in_path, std::ios::binary);
        orig.assign(std::istreambuf_iterator<char>(g), std::istreambuf_iterator<char>());
    }
    CHECK(orig == logical);
    CHECK(back.find("ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=0 INITIAL=1") != std::string::npos);
    CHECK(back.find("ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=1\n") != std::string::npos);
    // The stream version over the same input gives the same bytes.
    std::istringstream is(logical);
    std::ostringstream os;
    rewrite_gcode(is, os, in);
    CHECK(os.str() == back);

    // A refusal leaves no sibling behind either.
    RewriteInput eight = u1_topology(8);
    {
        boost::nowide::ofstream f(in_path, std::ios::binary);
        f << start_gcode(0);
        int prev = 0;
        for (int t = 1; t < 8; ++t) {
            f << change(prev, t, t);
            prev = t;
        }
        f << end_gcode();
    }
    fs::remove(out_path);
    CHECK_THROWS_AS(rewrite_file(in_path, out_path, eight), RewriteRefusal);
    CHECK_FALSE(fs::exists(out_path));
    // And a missing input is a refusal, not a crash.
    CHECK_THROWS_AS(rewrite_file((dir / "absent.gcode").string(), out_path, in), RewriteRefusal);

    boost::system::error_code ec;
    fs::remove_all(dir, ec);
}

TEST_CASE("a plate that fits one filament per toolhead is never rearranged", "[ace_mmu_rewrite]")
{
    // The plate that found this: four filaments, three feeders and a four-bay ACE on the
    // last head. Every arrangement costs zero swaps, so the optimiser took an arbitrary one
    // and moved all four. Orca's own assignment ties, so it wins.
    RewriteInput in = u1_topology(4);
    std::string  g  = start_gcode(0);
    int          prev = 0;
    const int    seq[] = {1, 2, 3, 0, 3, 1, 2, 0, 3, 2, 1, 0};
    int          layer = 0;
    for (int t : seq) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);                       // head 4 is ACE-fed, so it needs its preload
    CHECK(r.plan.head_of == std::vector<int>{0, 1, 2, 3});
    CHECK(r.plan.swaps == 0);
    CHECK(r.swaps == 0);
    CHECK(r.preload_slot == std::vector<int>{-1, -1, -1, 0});
    // and the file still selects the same physical heads it always did
    const auto out = lines_of(os.str());
    CHECK(count_prefix(out, "T3") == count_prefix(lines_of(g), "T3"));
    CHECK(index_of(out, "; multiACE plan: T0:H0S0 T1:H1S0 T2:H2S0 T3:H3S0 swaps:0 optimal:1") >= 0);
}

TEST_CASE("the optimiser still wins when it is actually cheaper", "[ace_mmu_rewrite]")
{
    // Five filaments on four heads: one pair has to share the ACE, and which pair matters.
    // The identity cannot even place the fifth, so there is nothing to tie with.
    RewriteInput in = u1_topology(5);
    std::string  g  = start_gcode(0);
    int          prev = 0;
    const int    seq[] = {1, 0, 1, 0, 1, 0, 2, 3, 4, 2, 3, 4, 1, 0};
    int          layer = 0;
    for (int t : seq) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.plan.feasible);
    CHECK(r.plan.head_of[4] >= 0);              // the fifth got a place
    // the busy alternating pair is not the one parked behind the changer
    CHECK(r.plan.head_of[0] != r.plan.head_of[1]);
}

TEST_CASE("a chosen bay is honoured and the displaced filament moves", "[ace_mmu_rewrite]")
{
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};                  // both on the ACE head
    in.flush_matrix  = {0.f, 100.f, 120.f, 0.f};
    std::string g    = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();

    // Unchosen, the planner puts filament 1 in bay 1 (first use) and filament 0 in bay 2.
    {
        std::istringstream is(g);
        std::ostringstream os;
        RewriteResult      r = rewrite_gcode(is, os, in);
        CHECK(r.plan.slot_of == std::vector<int>{1, 0});
    }

    // Ask for filament 1 in bay 3. Nothing was in bay 3, so nothing has to move: a
    // filament is displaced only when the bay it sits in is the one being claimed.
    {
        RewriteInput free_bay = in;
        free_bay.slot_override = { -1, 2 };
        std::istringstream is(g);
        std::ostringstream os;
        RewriteResult      r = rewrite_gcode(is, os, free_bay);
        REQUIRE(r.rewritten);
        CHECK(r.plan.slot_of == std::vector<int>{1, 2});
        // Addressing is not a cost: the head presents a different bay just as often.
        CHECK(r.swaps == 2);
        const auto out = lines_of(os.str());
        CHECK(index_of(out, "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=2 INITIAL=1") >= 0);
        CHECK(index_of(out, "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=1") >= 0);
        CHECK(r.header_line == "; multiACE plan: T0:H3S1 T1:H3S2 swaps:2 optimal:0");
    }

    // Now claim the bay filament 0 is sitting in. It has to go somewhere, and the lowest
    // free bay of the same head is where.
    {
        RewriteInput taken = in;
        taken.slot_override = { -1, 1 };
        std::istringstream is(g);
        std::ostringstream os;
        RewriteResult      r = rewrite_gcode(is, os, taken);
        REQUIRE(r.rewritten);
        CHECK(r.plan.slot_of[1] == 1);
        CHECK(r.plan.slot_of[0] == 0);
        CHECK(r.swaps == 2);
    }
}

TEST_CASE("a bay that cannot be honoured is refused, never quietly dropped", "[ace_mmu_rewrite]")
{
    RewriteInput base = u1_topology(2);
    base.head_override = {3, 3};
    const std::string g = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();
    auto run = [&](RewriteInput in) {
        std::istringstream is(g);
        std::ostringstream os;
        return rewrite_gcode(is, os, in);
    };

    RewriteInput both = base; both.slot_override = {1, 1};
    REQUIRE_THROWS_WITH(run(both), Catch::Contains("both put in the same bay"));

    RewriteInput far = base; far.slot_override = {-1, 7};
    REQUIRE_THROWS_WITH(run(far), Catch::Contains("has 4 bays"));

    RewriteInput onFeeder = base; onFeeder.head_override = {0, 3}; onFeeder.slot_override = {2, -1};
    REQUIRE_THROWS_WITH(run(onFeeder), Catch::Contains("stock feeder"));

    RewriteInput wrongSize = base; wrongSize.slot_override = {0};
    REQUIRE_THROWS_WITH(run(wrongSize), Catch::Contains("name 1 filaments"));
}
