#include <catch2/catch.hpp>

#include "libslic3r/AceMmuRewrite.hpp"

#include <boost/filesystem.hpp>
#include <boost/nowide/fstream.hpp>

#include <cstdlib>
#include <sstream>
#include <string>
#include <vector>

using namespace Slic3r;
using namespace Slic3r::AceMmu;

// A logical file in the stock U1 template's shape: the start gcode with its two selections of
// the initial tool and the prime line, the layer -1 marker, then one block per tool change the
// way `change_filament_gcode` and OozePrevention write them.
namespace {

std::string start_gcode(int init)
{
    std::string s;
    s += "; HEADER_BLOCK_START\n; generated by Snapmaker Orca\n; HEADER_BLOCK_END\n\n";
    s += "; EXECUTABLE_BLOCK_START\n";
    s += ";===== date: 20260128 =====================\n\nPRINT_START\n";
    s += "M104 T" + std::to_string(init) + " S140\n";
    s += "G28 X Y\n;===== bed check ========\nT" + std::to_string(init) + "\nG90\n";
    s += "SM_PRINT_EXTRUDER_PREHEAT EXTRUDER=1 TEMP=140\nSM_PRINT_AUTO_FEED EXTRUDER=0\n";
    s += "M104 S0 T0 A0\nM104 S0 T1 A0\nM104 S0 T2 A0\nM104 S0 T3 A0\n";
    s += "M104 T" + std::to_string(init) + " S130\n\n;===== homing =================\nT" + std::to_string(init) + "\n";
    s += "M109 T" + std::to_string(init) + " S130\nG28 Z\n\n";
    s += ";===== \xe7\x94\xbb\xe8\xb5\xb7\xe5\xa7\x8b\xe7\xba\xbf =================\n";
    s += "G90\nG1 Z1.5\nG0 X85 Y1 Z2 F18000\nM109 S220\nG1 Z0.2\nM83\nG1 X185 E15 F360\nG1 Z1.5\n\nG90\nM106 S0\n";
    s += "G21\nM83 ; use relative distances for extrusion\n";
    s += ";===== date: 20251213=====================\n";
    s += "; Change Tool" + std::to_string(init) + " -> Tool" + std::to_string(init) + " (layer -1)\n";
    s += "G91\nG1 Z1.5 F1800\nG90\nG1 F21000\nM400\nT" + std::to_string(init) + "\nG90\n";
    s += ";LAYER_CHANGE\n;Z:0.25\nG1 X10 Y10 F3000\nG1 X20 Y10 E0.5\n";
    return s;
}

std::string change(int prev, int next, int layer, bool preextrude = true)
{
    std::string s;
    s += "M104 S70 T" + std::to_string(prev) + " ; set nozzle temperature ;cooldown\n";
    s += ";===== date: 20251213=====================\n";
    s += "; Change Tool" + std::to_string(prev) + " -> Tool" + std::to_string(next) + " (layer " + std::to_string(layer) + ")\n";
    s += "G91\nG1 Z1.5 F1800\nG90\nG1 F21000\n\n; " + std::to_string(layer) + "\n";
    s += "M109 S220 T" + std::to_string(next) + "\nM400\nT" + std::to_string(next) + "\n";
    if (preextrude)
        s += "SM_PRINT_PREEXTRUDE_FILAMENT INDEX=" + std::to_string(next) + "\n";
    s += "G90\nM104 S220 T" + std::to_string(next) + " ; set nozzle temperature\n";
    s += "G1 X20 Y20 E0.5\nG1 X30 Y20 E0.5\n";
    return s;
}

std::string end_gcode()
{
    return "M104 S0\nM140 S0\n; EXECUTABLE_BLOCK_END\n\n; CONFIG_BLOCK_START\n; flush_multiplier = 1\n; CONFIG_BLOCK_END\n";
}

// The U1 as the reference machine has it: three stock feeders and one four-bay ACE on head 4.
RewriteInput u1_topology(int filaments)
{
    RewriteInput in;
    in.mode          = "head";
    in.head_unit     = {-1, -1, -1, 0};
    in.head_capacity = {1, 1, 1, 4};
    static const char* colours[] = {"#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff", "#00ffff", "#000000", "#ffffff"};
    for (int i = 0; i < filaments; ++i) {
        RewriteFilament f;
        f.colour = colours[i % 8];
        f.type   = "PLA";
        in.filaments.push_back(f);
    }
    return in;
}

std::vector<std::string> lines_of(const std::string& s)
{
    std::vector<std::string> out;
    std::istringstream       is(s);
    std::string              l;
    while (std::getline(is, l))
        out.push_back(l);
    return out;
}

// With ACE_REWRITE_KEEP_DIR set, a case's input and output are kept as files, for
// docs/u1-webui/tools/ace_rewrite_diff.py to run multiACE's own rewriter over.
void keep_pair(const std::string& name, const std::string& logical, const std::string& sibling)
{
    const char* dir = std::getenv("ACE_REWRITE_KEEP_DIR");
    if (dir == nullptr || *dir == '\0')
        return;
    boost::filesystem::create_directories(dir);
    boost::nowide::ofstream a((boost::filesystem::path(dir) / (name + ".logical.gcode")).string(), std::ios::binary);
    a << logical;
    boost::nowide::ofstream b((boost::filesystem::path(dir) / (name + ".ace.gcode")).string(), std::ios::binary);
    b << sibling;
}

int count_prefix(const std::vector<std::string>& lines, const std::string& pfx)
{
    int n = 0;
    for (const auto& l : lines)
        if (l.compare(0, pfx.size(), pfx) == 0)
            ++n;
    return n;
}

int index_of(const std::vector<std::string>& lines, const std::string& exact, int from = 0)
{
    for (int i = from; i < int(lines.size()); ++i)
        if (lines[i] == exact)
            return i;
    return -1;
}

int index_containing(const std::vector<std::string>& lines, const std::string& part, int from = 0)
{
    for (int i = from; i < int(lines.size()); ++i)
        if (lines[i].find(part) != std::string::npos)
            return i;
    return -1;
}

} // namespace

TEST_CASE("pass A reads the initial tool, the body sequence and the anchor", "[ace_mmu_rewrite]")
{
    std::string g = start_gcode(1) + change(1, 4, 0) + change(4, 2, 0) + change(2, 1, 1) + change(1, 5, 1) + end_gcode();
    std::istringstream in(g);
    ToolSequence       seq = scan_tool_sequence(in);
    CHECK(seq.initial == 1);
    CHECK(seq.body == std::vector<int>{1, 4, 2, 1, 5});
    CHECK(seq.used == std::vector<int>{1, 2, 4, 5});
    CHECK(seq.max_tool == 5);
    const auto lines = lines_of(g);
    CHECK(seq.first_marker == index_of(lines, "; Change Tool1 -> Tool1 (layer -1)"));
    CHECK(seq.first_extruding == index_of(lines, "G1 X185 E15 F360"));
    // The boundary right before the prime line is the prime section's own header.
    CHECK(seq.anchor == index_containing(lines, "\xe7\x94\xbb\xe8\xb5\xb7\xe5\xa7\x8b\xe7\xba\xbf"));
    CHECK(seq.anchor < seq.first_extruding);
    CHECK(seq.anchor < seq.first_marker);
}

TEST_CASE("an ordinary plate on stock feeders is left exactly as it is", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(3);
    std::string  g  = start_gcode(0) + change(0, 1, 0) + change(1, 2, 0) + change(2, 0, 1) + end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    CHECK_FALSE(r.rewritten);
    CHECK(os.str().empty());
    REQUIRE(r.plan.feasible);
    CHECK(r.plan.swaps == 0);
    CHECK(r.plan.head_of == std::vector<int>{0, 1, 2});
}

TEST_CASE("normal mode never rewrites", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(2);
    in.mode         = "normal";
    std::istringstream is(start_gcode(0) + change(0, 1, 0) + end_gcode());
    std::ostringstream os;
    CHECK_FALSE(rewrite_gcode(is, os, in).rewritten);
    CHECK(os.str().empty());
}

TEST_CASE("a two-filament plate forced onto the ACE head, line by line", "[ace_mmu_rewrite]")
{
    // Both filaments on head 4 (index 3), so every change is a bay swap and the output is
    // fully determined: this pins the exact emission format.
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};
    in.flush_matrix  = {0.f, 100.f, 120.f, 0.f}; // mm3, [from * 2 + to]
    std::string g    = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    CHECK(r.plan.head_of == std::vector<int>{3, 3});
    CHECK(r.plan.slot_of == std::vector<int>{1, 0}); // first-use order: filament 1 first
    CHECK(r.swaps == 2);
    CHECK(r.plan.swaps == 2);
    CHECK(r.preload_slot == std::vector<int>{-1, -1, -1, 0});
    CHECK(r.runs[3] == std::vector<int>{1, 0});

    const auto out = lines_of(os.str());
    const auto src = lines_of(g);
    CHECK(out.size() == src.size() + 6 /* block */ + 2 * 3 /* two swaps: comment, stamp, swap */ - 2 /* both pre-extrudes dropped */);

    // The start gcode: only the initial tool's references move, the physical shutdowns stay.
    CHECK(index_of(out, "M104 T3 S140") >= 0);
    CHECK(index_of(out, "M104 T1 S140") < 0);
    CHECK(index_of(out, "M104 S0 T1 A0") >= 0);
    CHECK(index_of(out, "M104 S0 T3 A0") >= 0);
    CHECK(index_of(out, "M104 T3 S130") >= 0);
    CHECK(index_of(out, "M109 T3 S130") >= 0);
    CHECK(index_of(out, "M109 S220") >= 0);
    CHECK(count_prefix(out, "T1") == 0);
    CHECK(count_prefix(out, "T3") == 5); // two start-gcode selections + layer -1 + two changes

    // The preload block sits right before the prime section's header.
    const int hdr = index_of(out, "; multiACE plan: T0:H3S1 T1:H3S0 swaps:2 optimal:0");
    REQUIRE(hdr >= 0);
    CHECK(out[hdr + 1] == "; multiACE auto-load: load 1 head(s)");
    CHECK(out[hdr + 2] == "; multiACE processed: format=4");
    CHECK(out[hdr + 3] == "ACE_SET_PURGE RESET=1");
    CHECK(out[hdr + 4] == "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=0 INITIAL=1");
    CHECK(out[hdr + 5] == "; multiACE auto-load: end");
    CHECK(out[hdr + 6].find("\xe7\x94\xbb\xe8\xb5\xb7\xe5\xa7\x8b\xe7\xba\xbf") != std::string::npos);

    // The layer -1 selection of the preloaded filament is a bare T3 and nothing else.
    const int m1 = index_of(out, "; Change Tool1 -> Tool1 (layer -1)");
    REQUIRE(m1 >= 0);
    const int t1 = index_of(out, "T3", m1);
    CHECK(out[t1 + 1] == "G90");

    // The first change: 1 -> 0 on the same head is a swap with the slicer's pair length.
    const int c0 = index_of(out, "; Change Tool1 -> Tool0 (layer 0)");
    REQUIRE(c0 >= 0);
    CHECK(out[c0 - 2] == "M104 S70 T3 ; set nozzle temperature ;cooldown");
    CHECK(index_of(out, "M109 S220 T3", c0) == c0 + 7);
    const int t0 = index_of(out, "T3", c0);
    CHECK(out[t0 + 1] == "; multiACE: head 3 must present ACE 0 slot 1");
    CHECK(out[t0 + 2] == "ACE_SET_PURGE LENGTH=" + std::to_string(purge_arg(purge_length_mm(in, 1, 0))));
    CHECK(out[t0 + 3] == "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=1");
    // The pre-extrude after a swap is dropped (the swap flushes); the head was primed by the
    // start gcode.
    CHECK(out[t0 + 4] == "G90");
    CHECK(out[t0 + 5] == "M104 S220 T3 ; set nozzle temperature");

    const double mm10 = purge_length_mm(in, 1, 0);
    CHECK(mm10 == Approx(120. / (3.14159265358979 * 0.25 * 1.75 * 1.75)));
    CHECK(purge_arg(mm10) == 50);
    CHECK(purge_arg(purge_length_mm(in, 0, 1)) == 42);
    CHECK(r.stamped == 2);
    CHECK(r.purge_mm == Approx(mm10 + purge_length_mm(in, 0, 1)));
    CHECK(r.purge_g == Approx((120. + 100.) * 1.24 / 1000.));
    CHECK(r.preflight_purge_mm == Approx(40. + 40.)); // both under the 40 mm floor
    CHECK(count_prefix(out, "SM_PRINT_PREEXTRUDE_FILAMENT") == 0);
    CHECK(r.dropped_standbys == 0);
    CHECK(r.header_line == out[hdr]);
    keep_pair("two-on-ace", g, os.str());
}

TEST_CASE("seven filaments over three feeders and a four-bay head", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(7);
    in.flush_matrix.assign(49, 140.f);
    for (int i = 0; i < 7; ++i)
        in.flush_matrix[i * 7 + i] = 0.f;

    // Two busy colours that alternate, five rare ones - the shape the planner is for.
    std::string g = start_gcode(0);
    int         prev = 0;
    const int   seq[] = {1, 0, 1, 2, 0, 1, 3, 0, 1, 4, 0, 1, 5, 0, 1, 6, 0, 1, 2, 3, 0, 1, 4, 5, 6, 0};
    int         layer = 0;
    for (int t : seq) {
        g += change(prev, t, layer++);
        prev = t;
    }
    g += end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    REQUIRE(r.plan.feasible);
    CHECK(r.plan.optimal);
    const auto out = lines_of(os.str());

    // Every selection names a physical head and no tool the printer lacks.
    for (const auto& l : out) {
        if (l.size() >= 2 && l[0] == 'T' && isdigit((unsigned char) l[1]))
            CHECK(l.size() == 2);
        if (l.rfind("M109 S220 T", 0) == 0 || l.rfind("M104 S220 T", 0) == 0 || l.rfind("M104 S70 T", 0) == 0)
            CHECK(l[l.find(" T") + 2] <= '3');
    }
    CHECK(count_prefix(out, "T4") + count_prefix(out, "T5") + count_prefix(out, "T6") == 0);
    // The emitted swaps agree with the planner's count, and each one carries its stamp.
    CHECK(r.swaps == r.plan.swaps);
    CHECK(count_prefix(out, "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=") == r.swaps + 1); // + the preload
    CHECK(count_prefix(out, "ACE_SET_PURGE LENGTH=") == r.swaps);
    CHECK(r.stamped == r.swaps);
    CHECK(r.purge_mm == Approx(r.swaps * 140. / (3.14159265358979 * 0.25 * 1.75 * 1.75)));
    // Four filaments live on the ACE head, three on the feeders, and the busy pair never swaps.
    int on_ace = 0;
    for (int h : r.plan.head_of)
        on_ace += (h == 3);
    CHECK(on_ace == 4);
    CHECK(r.plan.head_of[0] != 3);
    CHECK(r.plan.head_of[1] != 3);
    CHECK(r.runs[3].size() == 4);
    // The header parses back to the same layout.
    LoadingPlan back;
    REQUIRE(parse_plan_header(r.header_line, back));
    CHECK(back.head_of == r.plan.head_of);
    CHECK(back.slot_of == r.plan.slot_of);
    CHECK(back.swaps == r.plan.swaps);
    CHECK(back.optimal == r.plan.optimal);
    // The feeders keep their pre-extrude at every change; the ACE head primes once at most.
    int ace_primes = 0, feeder_primes = 0;
    for (const auto& l : out)
        if (l.rfind("SM_PRINT_PREEXTRUDE_FILAMENT INDEX=", 0) == 0)
            (l.back() == '3' ? ace_primes : feeder_primes)++;
    CHECK(ace_primes <= 1);
    CHECK(feeder_primes > 0);
    CHECK(r.dropped_standbys == 0); // every cooldown here is followed by the M109 that re-heats
    keep_pair("seven", g, os.str());
}

TEST_CASE("a standby that would cool the printing head is dropped, and no other is", "[ace_mmu_rewrite]")
{
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};
    // Print-by-object shape: after the change to tool 0 the slicer parks the OTHER tool - which
    // shares the head - and prints on it at 70 C. That line, and only that line, goes.
    std::string g = start_gcode(1) + change(1, 0, 0);
    g += "M104 S70 T1 ; set nozzle temperature ;cooldown\n";
    g += "G1 X40 Y20 E0.5\n";
    g += change(0, 1, 1);
    g += end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    CHECK(r.dropped_standbys == 1);
    const auto out = lines_of(os.str());
    const int  c0  = index_of(out, "; Change Tool1 -> Tool0 (layer 0)");
    REQUIRE(c0 >= 0);
    // The cooldown before the change survives: the M109 six lines later re-heats the head.
    CHECK(out[c0 - 2] == "M104 S70 T3 ; set nozzle temperature ;cooldown");
    const int dropped = index_containing(out, "; multiACE dropped: M104 S70 T3 ; set nozzle temperature ;cooldown", c0);
    REQUIRE(dropped >= 0);
    CHECK(out[dropped].find("would cool the printing head below 170 C") != std::string::npos);
    CHECK(out[dropped + 1] == "G1 X40 Y20 E0.5");
    // And the change back to tool 1 keeps its own cooldown, which its M109 answers.
    const int c1 = index_of(out, "; Change Tool0 -> Tool1 (layer 1)");
    REQUIRE(c1 >= 0);
    CHECK(out[c1 - 2] == "M104 S70 T3 ; set nozzle temperature ;cooldown");
    keep_pair("standby", g, os.str());
}

TEST_CASE("more filaments than places is refused with the counts", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(8);
    std::string  g  = start_gcode(0);
    int          prev = 0;
    for (int t = 1; t < 8; ++t) {
        g += change(prev, t, t);
        prev = t;
    }
    g += change(7, 0, 8) + end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    REQUIRE_THROWS_AS(rewrite_gcode(is, os, in), RewriteRefusal);
    std::istringstream is2(g);
    try {
        rewrite_gcode(is2, os, in);
    } catch (const RewriteRefusal& e) {
        const std::string m = e.what();
        CHECK(m.find("8 filaments") != std::string::npos);
        CHECK(m.find("7 places") != std::string::npos);
        CHECK(m.find("3 stock feeder(s)") != std::string::npos);
        CHECK(m.find("4 ACE slot(s)") != std::string::npos);
        CHECK(m.find("Cheapest to drop") != std::string::npos);
    }
    CHECK(os.str().empty());
}

TEST_CASE("a tool the project has no filament for is refused", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(4);
    std::istringstream is(start_gcode(0) + change(0, 5, 0) + end_gcode());
    std::ostringstream os;
    REQUIRE_THROWS_WITH(rewrite_gcode(is, os, in), Catch::Contains("T5") && Catch::Contains("4 filament"));
}

TEST_CASE("combined mode and a shared unit are refused for now", "[ace_mmu_rewrite]")
{
    RewriteInput in = u1_topology(2);
    in.mode         = "multi";
    REQUIRE_THROWS_WITH(plan_heads(in), Catch::Contains("Combined"));
    in.mode          = "head";
    in.head_unit     = {-1, -1, 0, 0};
    in.head_capacity = {1, 1, 4, 4};
    REQUIRE_THROWS_WITH(plan_heads(in), Catch::Contains("share ACE 1"));
    in.head_unit     = {-1, -1, -1, -1};
    in.head_capacity = {1, 1, 1, 4};
    REQUIRE_THROWS_WITH(plan_heads(in), Catch::Contains("no ACE unit"));
}

TEST_CASE("the plan header round-trips", "[ace_mmu_rewrite]")
{
    LoadingPlan p;
    p.feasible = true;
    p.optimal  = true;
    p.swaps    = 300;
    p.head_of  = {3, 3, 0, 1, 2, 3, 3, -1};
    p.slot_of  = {3, 0, 0, 0, 0, 2, 1, -1};
    const std::string line = plan_header_line(p);
    CHECK(line == "; multiACE plan: T0:H3S3 T1:H3S0 T2:H0S0 T3:H1S0 T4:H2S0 T5:H3S2 T6:H3S1 swaps:300 optimal:1");
    LoadingPlan back;
    REQUIRE(parse_plan_header(line, back));
    CHECK(back.head_of == std::vector<int>{3, 3, 0, 1, 2, 3, 3});
    CHECK(back.slot_of == std::vector<int>{3, 0, 0, 0, 0, 2, 1});
    CHECK(back.swaps == 300);
    CHECK(back.optimal);
    CHECK(back.feasible);
    CHECK_FALSE(parse_plan_header("; multiACE plan: {\"json\": 1}", back));
    CHECK_FALSE(parse_plan_header("; something else", back));
}

TEST_CASE("the purge argument is what the macro can parse", "[ace_mmu_rewrite]")
{
    /*
     * multiACE: `length = gcmd.get_int('LENGTH', None, minval=0, maxval=200)`.
     *
     * A three-decimal figure is not a number Klipper will take here. It answered
     * `ACE_SET_PURGE LENGTH=32.179` with "unable to parse 32.179" and cancelled the print
     * at the first swap - on a real machine, on a real plate.
     */
    CHECK(purge_arg(47.271) == 47);
    CHECK(purge_arg(47.6) == 48);       // rounded, not truncated
    CHECK(purge_arg(80.) == 80);
    // 0 is the plugin's "use the stock default (80mm)", so a stamp never rounds into it.
    CHECK(purge_arg(0.4) == 1);
    CHECK(purge_arg(0.0004) == 1);
    // and the ceiling is the macro's, not ours: capped prints, unparsable does not.
    CHECK(purge_arg(200.) == 200);
    CHECK(purge_arg(1e9) == 200);
}

TEST_CASE("every emitted macro argument is an integer where the plugin parses one",
          "[ace_mmu_rewrite]")
{
    /*
     * The whole class, not the one instance. Every argument the rewriter writes goes to a
     * `gcmd.get_int` in ace.py - LENGTH, HEAD, ACE, SLOT - and one of them was a float for
     * as long as the rewriter has existed, because nothing checked the SHAPE of what was
     * emitted, only that the right macro appeared.
     */
    RewriteInput in = u1_topology(4);
    in.head_capacity = { 1, 1, 1, 4 };
    in.head_override = { 3, 1, 3, 2 };
    in.flush_multiplier = 3.;           // push the stamps up, toward the macro's ceiling
    for (auto& f : in.filaments)
        f.colour = "#123456";
    in.filaments[0].colour = "#FFFFFF";
    in.filaments[2].colour = "#000000";

    std::string g = start_gcode(0);
    int prev = 0, layer = 0;
    for (int t : {1, 2, 1, 2, 3, 0, 2, 0}) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);

    int checked = 0;
    for (const std::string& l : lines_of(os.str())) {
        if (l.rfind("ACE_", 0) != 0 && l.rfind("SM_PRINT_PREEXTRUDE", 0) != 0)
            continue;
        // Every KEY=VALUE on the line, with the values the plugin reads as ints.
        size_t at = 0;
        while ((at = l.find('=', at)) != std::string::npos) {
            size_t ks = l.rfind(' ', at);
            ks = (ks == std::string::npos) ? 0 : ks + 1;
            const std::string key = l.substr(ks, at - ks);
            size_t ve = l.find(' ', at + 1);
            const std::string val = l.substr(at + 1, ve == std::string::npos ? ve : ve - at - 1);
            at = at + 1;
            if (key != "LENGTH" && key != "HEAD" && key != "ACE" && key != "SLOT"
                && key != "INDEX" && key != "INITIAL" && key != "RESET")
                continue;
            ++checked;
            INFO("line: " << l << "  argument: " << key << "=" << val);
            CHECK(val.find('.') == std::string::npos);      // get_int takes no decimals
            CHECK(!val.empty());
            CHECK(val.find_first_not_of("-0123456789") == std::string::npos);
            if (key == "LENGTH") {
                const int v = std::atoi(val.c_str());
                CHECK(v >= 1);          // 0 would mean the stock 80mm default
                CHECK(v <= 200);        // the macro's own maxval
            }
        }
    }
    CHECK(checked > 0);                 // a pass on an empty walk is not a pass
}

TEST_CASE("rewrite_file writes the sibling only when there is something to write", "[ace_mmu_rewrite]")
{
    namespace fs = boost::filesystem;
    const fs::path dir = fs::temp_directory_path() / fs::unique_path("ace-rewrite-%%%%-%%%%");
    fs::create_directories(dir);
    const std::string in_path  = (dir / "plate.gcode").string();
    const std::string out_path = (dir / "plate.ace.gcode").string();

    // An ordinary plate: no sibling appears.
    {
        boost::nowide::ofstream f(in_path, std::ios::binary);
        f << start_gcode(0) << change(0, 1, 0) << change(1, 2, 0) << end_gcode();
    }
    RewriteResult r = rewrite_file(in_path, out_path, u1_topology(3));
    CHECK_FALSE(r.rewritten);
    CHECK_FALSE(fs::exists(out_path));

    // An ACE plate: the sibling is the rewritten file and the original is untouched.
    const std::string logical = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();
    {
        boost::nowide::ofstream f(in_path, std::ios::binary);
        f << logical;
    }
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};
    int ticks        = 0;
    r                = rewrite_file(in_path, out_path, in, [&ticks]() { ++ticks; });
    REQUIRE(r.rewritten);
    CHECK(r.swaps == 2);
    CHECK(ticks >= 2);
    REQUIRE(fs::exists(out_path));
    std::string back, orig;
    {
        boost::nowide::ifstream f(out_path, std::ios::binary);
        back.assign(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
        boost::nowide::ifstream g(in_path, std::ios::binary);
        orig.assign(std::istreambuf_iterator<char>(g), std::istreambuf_iterator<char>());
    }
    CHECK(orig == logical);
    CHECK(back.find("ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=0 INITIAL=1") != std::string::npos);
    CHECK(back.find("ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=1\n") != std::string::npos);
    // The stream version over the same input gives the same bytes.
    std::istringstream is(logical);
    std::ostringstream os;
    rewrite_gcode(is, os, in);
    CHECK(os.str() == back);

    // A refusal leaves no sibling behind either.
    RewriteInput eight = u1_topology(8);
    {
        boost::nowide::ofstream f(in_path, std::ios::binary);
        f << start_gcode(0);
        int prev = 0;
        for (int t = 1; t < 8; ++t) {
            f << change(prev, t, t);
            prev = t;
        }
        f << end_gcode();
    }
    fs::remove(out_path);
    CHECK_THROWS_AS(rewrite_file(in_path, out_path, eight), RewriteRefusal);
    CHECK_FALSE(fs::exists(out_path));
    // And a missing input is a refusal, not a crash.
    CHECK_THROWS_AS(rewrite_file((dir / "absent.gcode").string(), out_path, in), RewriteRefusal);

    boost::system::error_code ec;
    fs::remove_all(dir, ec);
}

TEST_CASE("a plate that fits one filament per toolhead is never rearranged", "[ace_mmu_rewrite]")
{
    // The plate that found this: four filaments, three feeders and a four-bay ACE on the
    // last head. Every arrangement costs zero swaps, so the optimiser took an arbitrary one
    // and moved all four. Orca's own assignment ties, so it wins.
    RewriteInput in = u1_topology(4);
    std::string  g  = start_gcode(0);
    int          prev = 0;
    const int    seq[] = {1, 2, 3, 0, 3, 1, 2, 0, 3, 2, 1, 0};
    int          layer = 0;
    for (int t : seq) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);                       // head 4 is ACE-fed, so it needs its preload
    CHECK(r.plan.head_of == std::vector<int>{0, 1, 2, 3});
    CHECK(r.plan.swaps == 0);
    CHECK(r.swaps == 0);
    CHECK(r.preload_slot == std::vector<int>{-1, -1, -1, 0});
    // and the file still selects the same physical heads it always did
    const auto out = lines_of(os.str());
    CHECK(count_prefix(out, "T3") == count_prefix(lines_of(g), "T3"));
    CHECK(index_of(out, "; multiACE plan: T0:H0S0 T1:H1S0 T2:H2S0 T3:H3S0 swaps:0 optimal:1") >= 0);
}

TEST_CASE("the optimiser still wins when it is actually cheaper", "[ace_mmu_rewrite]")
{
    // Five filaments on four heads: one pair has to share the ACE, and which pair matters.
    // The identity cannot even place the fifth, so there is nothing to tie with.
    RewriteInput in = u1_topology(5);
    std::string  g  = start_gcode(0);
    int          prev = 0;
    const int    seq[] = {1, 0, 1, 0, 1, 0, 2, 3, 4, 2, 3, 4, 1, 0};
    int          layer = 0;
    for (int t : seq) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.plan.feasible);
    CHECK(r.plan.head_of[4] >= 0);              // the fifth got a place
    // the busy alternating pair is not the one parked behind the changer
    CHECK(r.plan.head_of[0] != r.plan.head_of[1]);
}

TEST_CASE("a chosen bay is honoured and the displaced filament moves", "[ace_mmu_rewrite]")
{
    RewriteInput in  = u1_topology(2);
    in.head_override = {3, 3};                  // both on the ACE head
    in.flush_matrix  = {0.f, 100.f, 120.f, 0.f};
    std::string g    = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();

    // Unchosen, the planner puts filament 1 in bay 1 (first use) and filament 0 in bay 2.
    {
        std::istringstream is(g);
        std::ostringstream os;
        RewriteResult      r = rewrite_gcode(is, os, in);
        CHECK(r.plan.slot_of == std::vector<int>{1, 0});
    }

    // Ask for filament 1 in bay 3. Nothing was in bay 3, so nothing has to move: a
    // filament is displaced only when the bay it sits in is the one being claimed.
    {
        RewriteInput free_bay = in;
        free_bay.slot_override = { -1, 2 };
        std::istringstream is(g);
        std::ostringstream os;
        RewriteResult      r = rewrite_gcode(is, os, free_bay);
        REQUIRE(r.rewritten);
        CHECK(r.plan.slot_of == std::vector<int>{1, 2});
        // Addressing is not a cost: the head presents a different bay just as often.
        CHECK(r.swaps == 2);
        const auto out = lines_of(os.str());
        CHECK(index_of(out, "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=2 INITIAL=1") >= 0);
        CHECK(index_of(out, "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=1") >= 0);
        CHECK(r.header_line == "; multiACE plan: T0:H3S1 T1:H3S2 swaps:2 optimal:0");
    }

    // Now claim the bay filament 0 is sitting in. It has to go somewhere, and the lowest
    // free bay of the same head is where.
    {
        RewriteInput taken = in;
        taken.slot_override = { -1, 1 };
        std::istringstream is(g);
        std::ostringstream os;
        RewriteResult      r = rewrite_gcode(is, os, taken);
        REQUIRE(r.rewritten);
        CHECK(r.plan.slot_of[1] == 1);
        CHECK(r.plan.slot_of[0] == 0);
        CHECK(r.swaps == 2);
    }
}

TEST_CASE("a bay that cannot be honoured is refused, never quietly dropped", "[ace_mmu_rewrite]")
{
    RewriteInput base = u1_topology(2);
    base.head_override = {3, 3};
    const std::string g = start_gcode(1) + change(1, 0, 0) + change(0, 1, 1) + end_gcode();
    auto run = [&](RewriteInput in) {
        std::istringstream is(g);
        std::ostringstream os;
        return rewrite_gcode(is, os, in);
    };

    RewriteInput both = base; both.slot_override = {1, 1};
    REQUIRE_THROWS_WITH(run(both), Catch::Contains("both put in the same bay"));

    RewriteInput far = base; far.slot_override = {-1, 7};
    REQUIRE_THROWS_WITH(run(far), Catch::Contains("has 4 bays"));

    RewriteInput onFeeder = base; onFeeder.head_override = {0, 3}; onFeeder.slot_override = {2, -1};
    REQUIRE_THROWS_WITH(run(onFeeder), Catch::Contains("stock feeder"));

    RewriteInput wrongSize = base; wrongSize.slot_override = {0};
    REQUIRE_THROWS_WITH(run(wrongSize), Catch::Contains("name 1 filaments"));
}

/*
 * A real plate, on demand.
 *
 * The synthetic files above are the stock template's shape and they check the rules; they
 * cannot check that a plate Orca actually produced parses the way the rules assume. The
 * fixture for that is not committed - an 8 MB gcode is not a test fixture - so this reads
 * one when it is pointed at one and does nothing otherwise.
 *
 *   ACE_REWRITE_FILE=/path/plate.gcode  ACE_REWRITE_CAP=1,1,1,4  ACE_REWRITE_UNIT=-1,-1,-1,0 \
 *     build/tests/libslic3r/Release/libslic3r_tests "[ace_mmu_real]"
 *
 * It prints the plan line, which is the one thing worth reading off a real plate: which
 * toolhead each filament ended on, and which bay feeds the ACE-fed one.
 */
namespace {

/** A bay the machine asserts: tag-read or named by hand, never inferred. */
LoadedPlace bay(int unit, int slot, const char* hex, const char* mat = "PLA")
{
    LoadedPlace p;
    p.unit = unit; p.slot = slot; p.colour = hex; p.material = mat; p.trusted = true;
    return p;
}
LoadedPlace feeder(int head, const char* hex, const char* mat = "PLA")
{
    LoadedPlace p;
    p.head = head; p.colour = hex; p.material = mat; p.trusted = true;
    return p;
}

} // namespace

TEST_CASE("the plan follows what the machine holds when that costs nothing", "[ace_mmu_rewrite]")
{
    /*
     * The ChickenPark case, reduced. Four filaments, three feeders and a four-bay ACE on
     * the last head - so every arrangement costs zero swaps and only the machine can break
     * the tie. Orca's own order would put filament 4 behind the ACE, and no bay holds it.
     */
    RewriteInput in = u1_topology(4);
    in.filaments[0].colour = "#FFFFDC";   // cream    - in bay A3
    in.filaments[1].colour = "#6D1D32";   // maroon   - in bay A1
    in.filaments[2].colour = "#000000";   // black    - in toolhead 3's feeder
    in.filaments[3].colour = "#E2DEDB";   // grey     - nowhere
    in.loadout = { feeder(0, "#FFFF00"), feeder(1, "#00FF00"), feeder(2, "#000000"),
                   bay(0, 0, "#6D1D32"), bay(0, 2, "#FFFFDC") };

    std::string g = start_gcode(0);
    int prev = 0, layer = 0;
    for (int t : {1, 2, 3, 0, 3, 1, 2, 0}) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    CHECK(r.plan.swaps == 0);                       // still costs nothing to run
    CHECK(r.plan.head_of[2] == 2);                  // black stays on the feeder that holds it
    // One of the two colours the ACE actually has ends up behind the ACE, in ITS bay -
    // not the grey, which is in no bay at all.
    const int on_ace = int(std::count(r.plan.head_of.begin(), r.plan.head_of.end(), 3));
    CHECK(on_ace == 1);
    int aceFil = -1;
    for (int i = 0; i < 4; ++i) if (r.plan.head_of[i] == 3) aceFil = i;
    REQUIRE(aceFil >= 0);
    CHECK(aceFil != 3);
    CHECK(((aceFil == 0 && r.plan.slot_of[0] == 2) || (aceFil == 1 && r.plan.slot_of[1] == 0)));
    // and the preload names that bay, not bay 0 by habit
    const auto out = lines_of(os.str());
    CHECK(index_of(out, "ACE_SWAP_HEAD HEAD=3 ACE=0 SLOT=" + std::to_string(r.plan.slot_of[aceFil])
                        + " INITIAL=1") >= 0);
}

TEST_CASE("a machine that could not be asked changes nothing", "[ace_mmu_rewrite]")
{
    // The printer is off, so there is no loadout - and the plan is exactly the one the
    // tie-break gives on its own. A slice must never depend on a reachable printer.
    RewriteInput in = u1_topology(4);
    std::string  g  = start_gcode(0);
    int prev = 0, layer = 0;
    for (int t : {1, 2, 3, 0, 3, 1, 2, 0}) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    CHECK(r.plan.head_of == std::vector<int>{0, 1, 2, 3});
}

TEST_CASE("an inferred spool is not evidence to plan on", "[ace_mmu_rewrite]")
{
    // The same machine, except nothing about the bays was asserted - the colours were
    // derived. Planning onto a guess is worse than leaving the plate where its owner put
    // it, so the identity holds and the panel is left to say the bay differs.
    RewriteInput in = u1_topology(4);
    in.filaments[0].colour = "#FFFFDC";
    in.filaments[3].colour = "#E2DEDB";
    in.loadout = { bay(0, 0, "#6D1D32"), bay(0, 2, "#FFFFDC") };
    for (auto& p : in.loadout) p.trusted = false;

    std::string g = start_gcode(0);
    int prev = 0, layer = 0;
    for (int t : {1, 2, 3, 0}) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    CHECK(r.plan.head_of == std::vector<int>{0, 1, 2, 3});
}

TEST_CASE("a cheaper plan still wins over a better-served one", "[ace_mmu_rewrite]")
{
    /*
     * Five filaments on four heads: two must share the ACE, and which two decides the swap
     * count. The machine holds the busy pair in its bays, so matching the loadout would
     * park the two alternating colours behind the changer - correct by the second key and
     * ruinous by the first. Swaps come first for exactly this case.
     */
    RewriteInput in = u1_topology(5);
    in.filaments[0].colour = "#AA0000";
    in.filaments[1].colour = "#00AA00";
    in.loadout = { bay(0, 0, "#AA0000"), bay(0, 1, "#00AA00") };
    std::string g = start_gcode(0);
    int prev = 0, layer = 0;
    for (int t : {1, 0, 1, 0, 1, 0, 2, 3, 4, 2, 3, 4, 1, 0}) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();
    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.plan.feasible);
    CHECK(r.plan.head_of[0] != r.plan.head_of[1]);  // the alternating pair is not stacked
}

TEST_CASE("an ACE head is primed on every return, like any other head", "[ace_mmu_rewrite]")
{
    /*
     * Two filaments share the ACE head and alternate with a feeder head, so the ACE head is
     * parked and comes back four times while presenting the SAME bay each time.
     *
     * Only the return that carries a swap is flushed by it. The other three are ordinary
     * returns to a parked head, and the stock pre-extrude is what primes them - a
     * stock-feeder head gets one every time, and there is no reason an ACE head needs less.
     * The suppression was a latch, so the head was marked primed for the rest of the file
     * after its first flush and printed the remaining returns cold.
     */
    RewriteInput in = u1_topology(4);
    in.head_capacity = { 1, 1, 1, 4 };
    // Filaments 0 and 2 both behind the ACE; 1 and 3 on feeders.
    in.head_override = { 3, 1, 3, 2 };

    std::string g = start_gcode(0);
    int prev = 0, layer = 0;
    for (int t : {1, 2, 1, 2, 1, 2, 1, 2}) { g += change(prev, t, layer++); prev = t; }
    g += end_gcode();

    std::istringstream is(g);
    std::ostringstream os;
    RewriteResult      r = rewrite_gcode(is, os, in);
    REQUIRE(r.rewritten);
    REQUIRE(r.plan.head_of[0] == 3);
    REQUIRE(r.plan.head_of[2] == 3);

    const auto out = lines_of(os.str());
    // Walk the body: every selection of the ACE head must be followed by a flush - either a
    // swap (which purges) or the prime the logical file had there. Never by neither.
    int returns = 0, flushed = 0, by_swap = 0, by_prime = 0;
    // The body only. The start gcode selects the initial head three times - to check the bed,
    // to home, and at the layer -1 marker - and its prime line is what primes that one.
    size_t body = 0;
    while (body < out.size() && out[body] != ";LAYER_CHANGE") ++body;
    REQUIRE(body < out.size());
    for (size_t i = body; i < out.size(); ++i) {
        if (out[i] != "T3")
            continue;
        bool swap = false, prime = false;
        for (size_t j = i + 1; j < out.size() && j < i + 5; ++j) {
            if (out[j].rfind("ACE_SWAP_HEAD", 0) == 0)                swap  = true;
            if (out[j].rfind("SM_PRINT_PREEXTRUDE_FILAMENT", 0) == 0) prime = true;
            if (out[j] == "T3" || (out[j].size() == 2 && out[j][0] == 'T')) break;
        }
        ++returns;
        if (swap || prime) ++flushed;
        if (swap)  ++by_swap;
        if (prime) ++by_prime;
    }
    CHECK(returns == flushed);          // no return to the ACE head arrives cold
    CHECK(by_swap == r.plan.swaps);     // the swaps are where the plan says
    CHECK(by_prime > 0);                // and the rest are primed, which is the regression
    // A swap already purges, so it never carries a prime on top of it.
    for (size_t i = 0; i + 1 < out.size(); ++i)
        if (out[i].rfind("ACE_SWAP_HEAD", 0) == 0)
            CHECK(out[i + 1].rfind("SM_PRINT_PREEXTRUDE_FILAMENT", 0) != 0);
}

TEST_CASE("a real plate, when one is pointed at", "[ace_mmu_real]")
{
    const char* path = std::getenv("ACE_REWRITE_FILE");
    if (path == nullptr || !*path) {
        WARN("ACE_REWRITE_FILE not set - nothing to read");
        return;
    }
    auto ints = [](const char* env, const char* fallback) {
        const char*      raw = std::getenv(env);
        std::string      s(raw && *raw ? raw : fallback);
        std::vector<int> out;
        size_t           at = 0;
        while (at <= s.size()) {
            const size_t comma = s.find(',', at);
            out.push_back(std::atoi(s.substr(at, comma == std::string::npos ? std::string::npos : comma - at).c_str()));
            if (comma == std::string::npos) break;
            at = comma + 1;
        }
        return out;
    };

    RewriteInput in;
    in.mode          = "head";
    in.head_capacity = ints("ACE_REWRITE_CAP", "1,1,1,4");
    in.head_unit     = ints("ACE_REWRITE_UNIT", "-1,-1,-1,0");

    /* A forced layout: filament -> toolhead, one per filament, `-1` to leave it to the
       planner. This is how a plate with two colours behind the changer gets built for a
       test before any control in the dialog offers it. */
    if (const char* heads = std::getenv("ACE_REWRITE_HEADS"); heads != nullptr && *heads)
        in.head_override = ints("ACE_REWRITE_HEADS", "");

    /* What the machine holds, so a real plate can be planned against a real loadout:
       ACE_REWRITE_BAYS="unit:slot:#rrggbb:MAT,..."  and the same for feeders as head:. */
    if (const char* bays = std::getenv("ACE_REWRITE_BAYS"); bays != nullptr && *bays) {
        std::string       spec(bays);
        std::stringstream ss(spec);
        std::string       one;
        while (std::getline(ss, one, ',')) {
            std::stringstream fs(one);
            std::string       a, b, c, d;
            std::getline(fs, a, ':'); std::getline(fs, b, ':');
            std::getline(fs, c, ':'); std::getline(fs, d, ':');
            LoadedPlace place;
            place.unit    = std::atoi(a.c_str());
            place.slot    = std::atoi(b.c_str());
            place.colour  = c;
            place.material = d.empty() ? "PLA" : d;
            place.trusted = true;
            in.loadout.push_back(place);
        }
    }

    // The plate's own filaments, read out of the file it carries them in.
    boost::nowide::ifstream f(path);
    REQUIRE(f.is_open());
    /*
     * The FLUSH matrix too, and it is not a detail.
     *
     * Without it every pair prices at 0, no `ACE_SET_PURGE LENGTH=` is written, and the
     * run reports "purge stamps: 0" - so the one argument that has actually broken a print
     * on this machine was the one thing a real plate could not exercise. It sat green
     * through the whole of it.
     */
    std::string line, types, colours, matrix, multiplier, diameters, densities;
    while (std::getline(f, line)) {
        auto take = [&line](const char* key, std::string& into) {
            const std::string k = std::string("; ") + key + " = ";
            if (into.empty() && line.rfind(k, 0) == 0) into = line.substr(k.size());
        };
        take("filament_type", types);
        take("filament_colour", colours);
        take("flush_volumes_matrix", matrix);
        take("flush_multiplier", multiplier);
        take("filament_diameter", diameters);
        take("filament_density", densities);
    }
    f.close();
    REQUIRE_FALSE(types.empty());
    auto split = [](std::string v) {
        std::vector<std::string> out;
        size_t                   at = 0;
        while (at <= v.size()) {
            const size_t sep = v.find_first_of(";,", at);
            out.push_back(v.substr(at, sep == std::string::npos ? std::string::npos : sep - at));
            if (sep == std::string::npos) break;
            at = sep + 1;
        }
        return out;
    };
    const auto ty = split(types), co = split(colours);
    const auto di = split(diameters), de = split(densities);
    for (size_t i = 0; i < ty.size(); ++i) {
        RewriteFilament fil;
        fil.type   = ty[i];
        fil.colour = i < co.size() ? co[i] : "";
        if (i < di.size() && !di[i].empty()) fil.diameter = std::atof(di[i].c_str());
        if (i < de.size() && !de[i].empty()) fil.density  = std::atof(de[i].c_str());
        in.filaments.push_back(fil);
    }
    if (!multiplier.empty())
        in.flush_multiplier = std::atof(multiplier.c_str());
    for (const std::string& v : split(matrix))
        if (!v.empty())
            in.flush_matrix.push_back(std::atof(v.c_str()));
    WARN("flush: " << in.flush_matrix.size() << " pair(s), multiplier "
                   << in.flush_multiplier);

    const std::string out = std::string(path) + ".ace.gcode";
    RewriteResult     r   = rewrite_file(path, out, in);
    // Whatever this plate turns out to be, what it WROTE has to be parsable.
    {
        boost::nowide::ifstream w(out);
        std::string             l;
        int                     stamps = 0;
        while (std::getline(w, l)) {
            const std::string k = "ACE_SET_PURGE LENGTH=";
            const size_t      at = l.find(k);
            if (at == std::string::npos) continue;
            const std::string v = l.substr(at + k.size());
            ++stamps;
            INFO("stamp: " << l);
            CHECK(v.find('.') == std::string::npos);   // get_int takes no decimals
            const int mm = std::atoi(v.c_str());
            CHECK(mm >= 1);
            CHECK(mm <= 200);
        }
        WARN("purge stamps written: " << stamps);
    }
    WARN("plate: " << path);
    WARN("filaments: " << in.filaments.size() << "  heads: " << in.head_capacity.size());
    WARN("PLAN LINE: " << (r.rewritten ? r.header_line : std::string("(no rewrite needed)")));
    WARN("swaps: " << r.swaps << "  purge stamps: " << r.stamped
                   << "  standbys dropped: " << r.dropped_standbys);
    CHECK(r.plan.feasible);
}
