#!/usr/bin/env python3
"""Generate the SSWCP command reference markdown from SSWCP.cpp + the bundle.

Reads:
  - src/slic3r/GUI/SSWCP.cpp   (dispatch, handler bodies, routing groups)
  - resources/web/flutter_web/main.dart.js (which commands the page actually calls)
Writes a grouped markdown table: command -> handler -> params -> response keys.
"""
import re, json, sys, os, collections

ROOT = sys.argv[1] if len(sys.argv) > 1 else "/home/gordian/proj/OrcaSlicer"
CPP  = f"{ROOT}/src/slic3r/GUI/SSWCP.cpp"
DART = f"{ROOT}/resources/web/flutter_web/main.dart.js"
OUT  = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "04-bridge-wcp", "03-command-parameters.md")

cpp = open(CPP, encoding='utf-8', errors='replace').read()
dart_cmds = set(re.findall(r'"(sw_[A-Za-z0-9_]+)"', open(DART, encoding='utf-8', errors='replace').read()))

# --- routing groups: static unordered_set<std::string> SSWCP::m_<group>_cmd_list = {...}
GROUP_LABEL = {
    "machine_find":    "Discovery",
    "machine_connect": "Connection",
    "machine_option":  "Machine control / files / camera",
    "project":         "Project & recent files",
    "login":           "Account, downloads & timelapse",
    "machine_manage":  "Saved-device management",
    "page_state":      "Page state",
    "mqtt_agent":      "Raw MQTT agent",
}
groups, defines = {}, dict(re.findall(r'#define\s+([A-Z_0-9]+)\s+"(sw_[A-Za-z0-9_]+)"', cpp))
for m in re.finditer(r'SSWCP::m_(\w+?)_cmd_list\s*=\s*\{(.*?)\};', cpp, re.S):
    g, body = m.group(1), m.group(2)
    for tok in re.findall(r'"(sw_[A-Za-z0-9_]+)"|\b([A-Z_0-9]{4,})\b', body):
        name = tok[0] or defines.get(tok[1])
        if name:
            groups[name] = g

# --- dispatch: m_cmd == "sw_X" -> handler()
dispatch = {}
for m in re.finditer(r'm_cmd\s*==\s*"(sw_[A-Za-z0-9_]+)"\s*\)\s*\{\s*(?:this->)?(\w+)\s*\(', cpp):
    dispatch[m.group(1)] = m.group(2)

# --- handler bodies
bodies = {}
for m in re.finditer(r'^[A-Za-z_][\w:<>,\s\*&]*\bSSWCP\w*::(\w+)\s*\([^;{]*\)\s*\{', cpp, re.M):
    start, d, k = m.end()-1, 0, m.end()-1
    while k < len(cpp):
        if cpp[k] == '{': d += 1
        elif cpp[k] == '}':
            d -= 1
            if d == 0: break
        k += 1
    bodies.setdefault(m.group(1), '')
    bodies[m.group(1)] += cpp[start:k]

def keys(body, var):
    return sorted(set(re.findall(re.escape(var)+r'\["([^"]+)"\]', body)) |
                  set(re.findall(re.escape(var)+r'\.count\("([^"]+)"\)', body)))

rows = collections.defaultdict(list)
for cmd in sorted(set(dispatch) | dart_cmds & set(dispatch)):
    h = dispatch.get(cmd, '')
    b = bodies.get(h, '')
    rows[groups.get(cmd, "common")].append({
        "cmd": cmd, "handler": h,
        "params": keys(b, "m_param_data"),
        "response": keys(b, "m_res_data"),
        "called_by_page": cmd in dart_cmds,
    })

order = ["machine_option","machine_connect","machine_find","machine_manage",
         "login","project","page_state","mqtt_agent","common"]
with open(OUT, 'w') as f:
    f.write("<!-- GENERATED by tools/gen_command_reference.py - do not edit by hand -->\n")
    f.write("# SSWCP command reference\n\n")
    f.write(f"{sum(len(v) for v in rows.values())} commands dispatched by "
            "`SSWCP_*::process()`. `page` = called by the Flutter Device page bundle.\n\n")
    for g in order:
        if g not in rows: continue
        f.write(f"## {GROUP_LABEL.get(g, g)}\n\n")
        f.write("| Command | page | C++ handler | Request `params` | Response `data` keys |\n")
        f.write("|---|:--:|---|---|---|\n")
        for r in sorted(rows[g], key=lambda x: x["cmd"]):
            p = ", ".join(f"`{x}`" for x in r["params"]) or "-"
            q = ", ".join(f"`{x}`" for x in r["response"]) or "-"
            f.write(f"| `{r['cmd']}` | {'yes' if r['called_by_page'] else ''} | "
                    f"`{r['handler']}()` | {p} | {q} |\n")
        f.write("\n")
print(f"groups: {len(rows)}  commands: {sum(len(v) for v in rows.values())}", file=sys.stderr)
