#!/usr/bin/env python3
"""Render data/jsonrpc-methods.json as the namespace-ordered RPC reference.

This is the generated *reference* view: every method, grouped by namespace, with
the literal parameter names recovered from the bundle. The hand-written
01-jsonrpc-methods.md groups the same surface by function and adds the async
notification channel; the two are complementary.

Writes: 05-printer-protocol/02-jsonrpc-reference.md
"""
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import DATA  # noqa: E402

DOC = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "05-printer-protocol", "02-jsonrpc-reference.md"))

ORIGIN = {
    "printer": "Klipper/Moonraker core, plus Snapmaker `printer.control.*`",
    "server": "Moonraker server API, plus Snapmaker `server.client_manager.*`",
    "machine": "Moonraker machine API",
    "camera": "**Snapmaker extension**",
    "custom": "**Snapmaker extension**",
    "system": "**Snapmaker extension**",
}


def main():
    d = json.load(open(os.path.join(DATA, "jsonrpc-methods.json"), encoding="utf-8"))
    groups = collections.defaultdict(list)
    for k, v in sorted(d.items()):
        groups[k.split(".")[0]].append(v)

    L = []
    A = L.append
    A("# JSON-RPC reference")
    A("")
    A("Generated by [`tools/gen_jsonrpc_reference.py`](../tools/gen_jsonrpc_reference.py)")
    A("from [`data/jsonrpc-methods.json`](../data/jsonrpc-methods.json). Do not edit by hand.")
    A("")
    A("Every method the bundle constructs, grouped by namespace. For the same surface")
    A("grouped by *function* — plus the printer's async notification channel — see")
    A("[JSON-RPC methods](01-jsonrpc-methods.md).")
    A("")
    A("Extraction works because dart2js lowers a Dart map literal to")
    A("`A.x([\"k1\",v1,\"k2\",v2,...])`, so an envelope appears literally as")
    A("`[\"jsonrpc\",\"2.0\",\"method\",\"<m>\",\"params\",A.x([...]),\"id\",<v>]`. Parameter names are")
    A("recoverable whenever the params map is a literal; where it is built at runtime the")
    A("method is still found but its params are marked *dynamic*.")
    A("")
    A(f"{len(d)} distinct methods across {len(groups)} namespaces.")
    A("")
    A("| Namespace | Methods | Origin |")
    A("|---|---|---|")
    for g in sorted(groups):
        A(f"| `{g}.*` | {len(groups[g])} | {ORIGIN.get(g, '')} |")
    A("")
    for g in sorted(groups):
        A(f"## `{g}.*`")
        A("")
        A("| Method | Params | Call sites |")
        A("|---|---|---|")
        for m in sorted(groups[g], key=lambda x: x["method"]):
            style = "/".join(m["param_style"])
            p = ", ".join(f"`{x}`" for x in m["params"]) if m["params"] else f"*{style}*"
            A(f"| `{m['method']}` | {p} | {m['call_sites']} |")
        A("")
    with open(DOC, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(DOC)}  ({len(d)} methods)")


if __name__ == "__main__":
    main()
