#!/usr/bin/env python3
"""Render data/error-codes.json as the legacy-error-asset reference.

This documents `assets/files/deviceError.json` - the 72-code, 8-hex-digit table
inherited from the Bambu-derived codebase. It is NOT the U1's live fault table;
that is the 442-code i18n catalogue built by extract_error_catalog.py.

Writes: 06-errors/02-legacy-error-asset.md
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import DATA  # noqa: E402

DOC = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "06-errors", "02-legacy-error-asset.md"))


def main():
    d = json.load(open(os.path.join(DATA, "error-codes.json"), encoding="utf-8"))
    L = []
    A = L.append
    A("# Legacy error asset (`deviceError.json`)")
    A("")
    A("> **This is the secondary table.** The U1's live faults are the 442-code,")
    A("> 16-hex-digit catalogue in [`01-live-error-catalogue.md`](01-live-error-catalogue.md),")
    A("> carried in the i18n table as `error_<16 hex>_title` / `_desc` pairs. The 72 codes")
    A("> below come from `assets/assets/files/deviceError.json`, an 8-hex-digit asset")
    A("> inherited from the Bambu-derived codebase — which is why several of its strings")
    A("> still say \"Bambu Cloud\" and \"AMS\". It ships, but it is not the live fault table.")
    A("")
    A("Generated by [`tools/gen_legacy_error_doc.py`](../tools/gen_legacy_error_doc.py) from")
    A("[`data/error-codes.json`](../data/error-codes.json). Do not edit by hand.")
    A("")
    A(f"{d['count']} codes, in `{'` and `'.join(d['locales'])}`.")
    A("")
    A("## Encoding")
    A("")
    A("Eight hex digits — note this is a *different* scheme from the live catalogue's")
    A("sixteen:")
    A("")
    A("```")
    A("  0300 4 000")
    A("  ^^^^ ^ ^^^")
    A("  |    | └── fault index within the subsystem")
    A("  |    └──── severity")
    A("  └───────── subsystem")
    A("```")
    A("")
    A("| Prefix | Count | Subsystem |")
    A("|---|---|---|")
    for p, v in d["by_subsystem"].items():
        A(f"| `{p}` | {v['count']} | {v['label']} |")
    A("")
    A("The `0700`–`0703` banks carry an identical nine-fault set, once per toolhead —")
    A("which is what identifies the third byte as a toolhead index.")
    A("")
    A("| Severity digit | Count | Meaning |")
    A("|---|---|---|")
    for dig, v in d["by_severity"].items():
        A(f"| `{dig}` | {v['count']} | {v['label']} |")
    A("")
    A("## Placeholders")
    A("")
    A(f"{len(d['placeholder_codes'])} codes ship with an **empty string in every locale** —")
    A("`xxxx8007` and `xxxx8010` in each of the four toolhead banks:")
    A("")
    A("```")
    A("  " + "  ".join(d["placeholder_codes"]))
    A("```")
    A("")
    A("## Full table")
    A("")
    A("| Code | Severity | Text (en) |")
    A("|---|---|---|")
    for c, e in sorted(d["errors"].items()):
        t = (e["text"].get("en") or "").replace("|", "\\|")
        if not t.strip():
            t = "*(empty — placeholder)*"
        A(f"| `{c}` | `{e['severity_digit']}` | {t} |")
    A("")
    with open(DOC, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(DOC)}  ({d['count']} codes)")


if __name__ == "__main__":
    main()
