#!/usr/bin/env python3
"""Emit the U1 fault catalogue as a JS module the reconstruction can import.

The 442-code catalogue is extracted from the bundle's i18n table by
extract_error_catalog.py. The Device page needs it at runtime to turn a raw
`action_code` into something a person can read, so it is emitted as data rather
than transcribed by hand.

Writes: resources/web/shared/js/errors.js
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import DATA, ROOT  # noqa: E402

OUT = os.path.join(ROOT, "resources", "web", "shared", "js", "errors.js")


def main():
    cat = json.load(open(os.path.join(DATA, "error-catalog.json"), encoding="utf-8"))
    codes = cat["codes"]
    subsystems = cat.get("subsystems", {})

    # keep it compact: [title, desc] per code
    table = {c: [v.get("en_title") or v.get("title") or "",
                 v.get("en_desc") or v.get("desc") or ""]
             for c, v in sorted(codes.items())}

    L = []
    A = L.append
    A("/*")
    A(" * errors.js - the U1 fault catalogue.")
    A(" *")
    A(" * GENERATED by docs/u1-webui/tools/gen_error_module.py from")
    A(" * docs/u1-webui/data/error-catalog.json. Do not edit by hand.")
    A(" *")
    A(" * Codes are 16 hex digits: SSSS MMMM UUUU EEEE")
    A(" *   class/severity, subsystem, unit index (toolhead), specific fault.")
    A(" * See docs/u1-webui/06-errors/01-live-error-catalogue.md")
    A(" */")
    A("'use strict';")
    A("")
    A("export const SUBSYSTEMS = " + json.dumps(subsystems, indent=1, sort_keys=True) + ";")
    A("")
    A(f"/** {len(table)} codes, [title, description]. */")
    A("export const FAULTS = " + json.dumps(table, indent=0, sort_keys=True) + ";")
    A("")
    A("""/** Decode a 16-hex-digit code into its four groups. */
export function decodeErrorCode(code) {
  const c = String(code == null ? '' : code).trim();
  if (!/^[0-9A-Fa-f]{16}$/.test(c)) return null;
  const subsystem = c.slice(4, 8);
  const unit = parseInt(c.slice(8, 12), 16);
  return {
    code: c.toUpperCase(),
    errorClass: c.slice(0, 4),
    subsystem,
    subsystemName: SUBSYSTEMS[subsystem] || 'unknown',
    unitIndex: unit,
    specific: c.slice(12, 16),
    // toolhead and filament faults number their head from the unit group
    toolhead: (subsystem === '0523' || subsystem === '0525') ? unit + 1 : null,
  };
}

/**
 * Look a fault up. Accepts the 16-digit form, and also a bare integer
 * `action_code`, which the state model reports as a number.
 */
export function lookupFault(code) {
  if (code == null || code === 0 || code === '') return null;
  let key = String(code).trim();
  if (/^[0-9]+$/.test(key) && key.length < 16) {
    key = Number(key).toString(16).toUpperCase().padStart(16, '0');
  }
  key = key.toUpperCase();
  const hit = FAULTS[key] || FAULTS[key.toLowerCase()];
  const parts = decodeErrorCode(key);
  if (!hit && !parts) return null;
  return {
    code: key,
    title: (hit && hit[0]) || 'Printer fault',
    description: (hit && hit[1]) || 'No description for this code in the shipped catalogue.',
    known: !!hit,
    ...(parts || {}),
  };
}""")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}  ({len(table)} codes, "
          f"{os.path.getsize(OUT):,} bytes)")


if __name__ == "__main__":
    main()
