#!/usr/bin/env python3
"""Render data/wcp-commands.json as the human-readable command catalogue.

Writes: 04-bridge-wcp/02-command-catalogue.md
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import DATA  # noqa: E402

DOC = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "04-bridge-wcp", "02-command-catalogue.md"))

GROUP_LABEL = {
    "machine_find": ("Machine discovery", "SSWCP_MachineFind_Instance"),
    "machine_connect": ("Connection and pairing", "SSWCP_MachineConnect_Instance"),
    "machine_option": ("Machine control, files, print jobs", "SSWCP_MachineOption_Instance"),
    "machine_manage": ("Saved-device management", "SSWCP_MachineManage_Instance"),
    "project": ("Projects and recent files", "SSWCP_SliceProject_Instance"),
    "login": ("Account", "SSWCP_UserLogin_Instance"),
    "mqtt_agent": ("MQTT transport agent", "SSWCP_MqttAgent_Instance"),
    "page_state": ("Page lifecycle", "SSWCP_PageStateChange_Instance"),
    None: ("Ungrouped — handled by the base instance", "SSWCP_Instance"),
}
ORDER = ["machine_find", "machine_connect", "machine_option", "machine_manage",
         "project", "login", "mqtt_agent", "page_state", None]


def main():
    cmds = json.load(open(os.path.join(DATA, "wcp-commands.json"), encoding="utf-8"))

    by_group = {}
    for c in cmds.values():
        by_group.setdefault(c.get("routing_group"), []).append(c)

    both = [c for c in cmds.values() if c["implemented_in_cpp"] and c["index"] is not None]
    page_only = [c for c in cmds.values() if not c["implemented_in_cpp"]]
    host_only = [c for c in cmds.values() if c["index"] is None]

    L = []
    L.append("# WCP command catalogue")
    L.append("")
    L.append("Generated by [`tools/gen_command_catalogue.py`](../tools/gen_command_catalogue.py)")
    L.append("from [`data/wcp-commands.json`](../data/wcp-commands.json). Do not edit by hand.")
    L.append("")
    L.append("Two independent sources are cross-referenced:")
    L.append("")
    L.append("- the page's `WcpCmd` enum, whose `gaX()` getter maps each enum index to a")
    L.append("  wire name (`sw_*`) and survives dart2js as a plain switch;")
    L.append("- `SSWCP.cpp` / `SSWCP.hpp`, which route each wire name to an instance class.")
    L.append("")
    L.append(f"| | Count |")
    L.append("|---|---|")
    L.append(f"| Commands in the page's `WcpCmd` enum | {len([c for c in cmds.values() if c['index'] is not None])} |")
    L.append(f"| Implemented by the C++ host | {len([c for c in cmds.values() if c['implemented_in_cpp']])} |")
    L.append(f"| Present on both sides | {len(both)} |")
    L.append(f"| Page-only — no host handler | {len(page_only)} |")
    L.append(f"| Host-only — absent from `WcpCmd` | {len(host_only)} |")
    L.append("")

    L.append("## Version skew")
    L.append("")
    L.append("The shipped bundle and the C++ host are versioned independently, and the")
    L.append("mismatch is visible in both directions.")
    L.append("")
    L.append("**Page-only** — the page can emit these, nothing answers them:")
    L.append("")
    L.append("| Wire name | `WcpCmd` value |")
    L.append("|---|---|")
    for c in sorted(page_only, key=lambda c: c["wire_name"]):
        L.append(f"| `{c['wire_name']}` | `{c['dart_enum_value'] or '—'}` |")
    L.append("")
    L.append("`sw_UnSubscribeMachineState` is worth singling out: the enum declares both it")
    L.append("(index 7) and `sw_StopMachineStateSubscription` (index 10), but the host")
    L.append("implements only the latter. A call on index 7 would go unanswered and fail on")
    L.append("the page's 3-second timeout.")
    L.append("")
    L.append("**Host-only** — implemented in C++, absent from the bundle's enum:")
    L.append("")
    for c in sorted(host_only, key=lambda c: c["wire_name"]):
        L.append(f"- `{c['wire_name']}`")
    L.append("")
    L.append("`sw_FinishPreprint`, `sw_GetPrintZip` and `sw_GetPrintLegal` belong to the")
    L.append("print-processing flow and *are* exercised at runtime, so the page reaches them")
    L.append("by some path other than a `WcpCmd` constant.")
    L.append("")

    L.append("## By routing group")
    L.append("")
    L.append("`SSWCP::create_sswcp_instance` picks an instance class by testing membership")
    L.append("in one of eight `unordered_set`s; anything unmatched falls through to the base")
    L.append("`SSWCP_Instance`.")
    L.append("")
    for g in ORDER:
        if g not in by_group:
            continue
        label, cls = GROUP_LABEL[g]
        rows = sorted(by_group[g], key=lambda c: c["wire_name"])
        L.append(f"### {label}")
        L.append("")
        L.append(f"`{cls}` — {len(rows)} commands")
        L.append("")
        L.append("| Wire name | `WcpCmd` value | Idx | Push channel | Host |")
        L.append("|---|---|---|---|---|")
        for c in rows:
            host = "yes" if c["implemented_in_cpp"] else "**no**"
            L.append(f"| `{c['wire_name']}` | `{c['dart_enum_value'] or '—'}` | "
                     f"{c['index'] if c['index'] is not None else '—'} | "
                     f"{('`'+c['push_channel']+'`') if c['push_channel'] else '—'} | {host} |")
        L.append("")

    with open(DOC, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(DOC)}  ({len(L)} lines, {len(cmds)} commands)")


if __name__ == "__main__":
    main()
