#!/usr/bin/env python3
"""Survey every MQTT topic a U1 publishes on, and what travels over each.

The connect path documented in 06-connection.md names four topics because those are the
four Orca subscribes to. That is what Orca uses, not what the printer offers. This
subscribes to the `#` wildcard instead and lets the printer enumerate itself.

Traffic is provoked in labelled phases - idle, a state subscription, a file listing, a
camera monitor - so each topic can be attributed to what caused it rather than guessed
at. For every topic it records the JSON-RPC methods seen, a field skeleton per method,
and one truncated sample.

Read-only: every method it sends queries, lists or subscribes. Nothing moves the machine
or touches a print job.

    python3 u1_topics.py                      # ~60s survey, prints a report
    python3 u1_topics.py --idle 30            # listen longer between phases
    python3 u1_topics.py --md ../topics.md    # write the markdown overview
"""

import argparse
import json
import os
import ssl
import sys
import time
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mqtt_min import MqttError                                   # noqa: E402
from u1_probe import (Session, device_from_orca_config, describe,  # noqa: E402
                      find_long_strings, LAN_AUTH_CODE)


class TopicSurvey:
    """Everything seen, bucketed by topic and then by JSON-RPC method."""

    def __init__(self):
        self.topics = OrderedDict()

    def record(self, topic, raw, phase):
        t = self.topics.setdefault(topic, {
            "count": 0, "bytes": 0, "phases": set(), "methods": OrderedDict(),
            "non_json": 0,
        })
        t["count"] += 1
        t["bytes"] += len(raw)
        t["phases"].add(phase)
        try:
            msg = json.loads(raw)
        except Exception:
            t["non_json"] += 1
            return None

        # notifications carry `method`; replies carry `id` and result/error
        if isinstance(msg, dict) and "method" in msg:
            key = msg["method"]
        elif isinstance(msg, dict) and "error" in msg:
            key = "<error reply>"
        elif isinstance(msg, dict) and ("result" in msg or "id" in msg):
            key = "<result reply>"
        else:
            key = "<bare payload>"

        m = t["methods"].setdefault(key, {"count": 0, "sample": None,
                                          "skeleton": None, "long": []})
        m["count"] += 1
        if m["sample"] is None:
            m["sample"] = json.dumps(msg)[:600]
            m["skeleton"] = describe(msg, max_depth=4)[:2000]
            m["long"] = find_long_strings(msg, minlen=256)[:4]
        return msg

    def drain(self, sess, seconds, phase):
        for topic, raw in sess.cli.messages(seconds):
            self.record(topic, raw, phase)

    # -- reporting -------------------------------------------------------

    def report(self):
        out = []
        for topic, t in sorted(self.topics.items()):
            out.append(f"\n{'=' * 78}\n{topic}")
            out.append(f"  {t['count']} message(s), {t['bytes']:,} bytes, "
                       f"seen during: {', '.join(sorted(t['phases']))}")
            if t["non_json"]:
                out.append(f"  {t['non_json']} non-JSON payload(s)")
            for name, m in sorted(t["methods"].items(),
                                  key=lambda kv: -kv[1]["count"]):
                out.append(f"\n  -- {name}  x{m['count']}")
                for line in (m["skeleton"] or "").split("\n")[:26]:
                    out.append(f"     {line}")
                for path, length, head in m["long"]:
                    out.append(f"     >> bulk at {path}  len={length}  {head!r}")
        return "\n".join(out)

    def markdown(self, dev, phases):
        L = ["# MQTT topics on a Snapmaker U1", "",
             "What the printer actually publishes, enumerated by subscribing to the `#`",
             "wildcard rather than to the four topics Orca happens to use. Generated by",
             "[`tools/u1_topics.py`](../tools/u1_topics.py) against real hardware.", "",
             f"Printer `{dev['sn']}` at `{dev['ip']}`. "
             f"Survey phases: {', '.join(phases)}.", "",
             "## Topics at a glance", "",
             "| Topic | Messages | Bytes | Carries |", "|---|---:|---:|---|"]
        for topic, t in sorted(self.topics.items()):
            methods = ", ".join(f"`{m}`" for m in list(t["methods"])[:4])
            if len(t["methods"]) > 4:
                methods += f", +{len(t['methods']) - 4} more"
            L.append(f"| `{topic}` | {t['count']} | {t['bytes']:,} | {methods or '-'} |")

        L += ["", "## Each topic in detail", ""]
        for topic, t in sorted(self.topics.items()):
            L += [f"### `{topic}`", "",
                  f"{t['count']} message(s), {t['bytes']:,} bytes. "
                  f"Observed during: {', '.join(sorted(t['phases']))}.", ""]
            for name, m in sorted(t["methods"].items(), key=lambda kv: -kv[1]["count"]):
                L += [f"#### `{name}` — {m['count']} message(s)", "",
                      "Shape:", "", "```", (m["skeleton"] or "").strip(), "```", ""]
                if m["long"]:
                    L.append("Bulk payload fields:")
                    L.append("")
                    for path, length, head in m["long"]:
                        L.append(f"- `{path}` — {length} chars, starts `{head}`")
                    L.append("")
                L += ["Sample:", "", "```json", m["sample"] or "", "```", ""]
        return "\n".join(L)


# ---------------------------------------------------------------------------- phases

def survey(sess, sv, idle):
    """Provoke traffic in labelled phases so topics can be attributed, not guessed."""
    phases = []

    def phase(name, seconds, before=None):
        phases.append(name)
        print(f"\n[{name}] ...", flush=True)
        if before:
            try:
                before()
            except Exception as e:
                print(f"  provoke failed: {type(e).__name__}: {e}")
        sv.drain(sess, seconds, name)
        print(f"  topics so far: {len(sv.topics)}")

    phase("idle", idle)

    phase("objects.list", 8,
          lambda: sess.cli.publish(f"{sess.sn}/request",
                                   sess.envelope("printer.objects.list", {})))

    # a broad state subscription is what makes <SN>/status talk
    watched = ["print_stats", "virtual_sdcard", "display_status", "heater_bed",
               "extruder", "toolhead", "gcode_move", "idle_timeout", "fan"]
    phase("objects.subscribe", max(idle, 15),
          lambda: sess.cli.publish(
              f"{sess.sn}/request",
              sess.envelope("printer.objects.subscribe",
                            {"objects": {o: None for o in watched}})))

    phase("files.get_directory", 8,
          lambda: sess.cli.publish(f"{sess.sn}/request",
                                   sess.envelope("server.files.get_directory",
                                                 {"path": "gcodes", "extended": True})))

    phase("timelapse.list", 8,
          lambda: sess.cli.publish(f"{sess.sn}/request",
                                   sess.envelope("camera.get_timelapse_instance",
                                                 {"page_index": 0, "page_rows": 4,
                                                  "thumbnail_direct": True})))

    # domain 'lan' is the value the printer accepts; '' is rejected -32000
    phase("camera.monitor", max(idle, 15),
          lambda: sess.cli.publish(f"{sess.sn}/request",
                                   sess.envelope("camera.start_monitor",
                                                 {"domain": "lan", "interval": 2,
                                                  "expect_pw": False})))
    sess.cli.publish(f"{sess.sn}/request",
                     sess.envelope("camera.stop_monitor", {"domain": "lan"}))
    sv.drain(sess, 4, "camera.monitor")

    phase("server.info", 8,
          lambda: sess.cli.publish(f"{sess.sn}/request",
                                   sess.envelope("server.info", {})))
    return phases


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ip")
    ap.add_argument("--sn")
    ap.add_argument("--client-id")
    ap.add_argument("--idle", type=int, default=12, help="seconds per listening phase")
    ap.add_argument("--md", help="write the markdown overview here")
    ap.add_argument("--json", help="write the raw survey here")
    ap.add_argument("--filter", default="#", help="topic filter (default: everything)")
    args = ap.parse_args()

    dev = {}
    if not (args.ip and args.sn and args.client_id):
        dev = device_from_orca_config() or {}
        if not dev:
            print("No device in Orca's config; pass --ip/--sn/--client-id.",
                  file=sys.stderr)
            return 2
    ip = args.ip or dev["ip"]
    sn = args.sn or dev["sn"]
    client_id = args.client_id or dev.get("clientId")
    print(f"surveying {sn} at {ip}")

    sess = Session(ip, sn, client_id)
    sv = TopicSurvey()
    try:
        sess.open(sess.request_keys())
    except (MqttError, OSError, ssl.SSLError) as e:
        print(f"connect failed: {type(e).__name__}: {e}", file=sys.stderr)
        sess.close()
        return 1

    try:
        # the whole point: let the printer enumerate its own topics
        try:
            sess.cli.subscribe(args.filter)
            print(f"  subscribed wildcard {args.filter!r}")
        except MqttError as e:
            print(f"  wildcard refused ({e}); falling back to the known topics")
            for t in (f"{sn}/status", f"{sn}/response", f"{sn}/notification",
                      f"{LAN_AUTH_CODE}/config/response",
                      f"{LAN_AUTH_CODE}/config/notification"):
                try:
                    sess.cli.subscribe(t)
                except MqttError:
                    pass
        phases = survey(sess, sv, args.idle)
    finally:
        sess.close()

    print(sv.report())
    print(f"\n{len(sv.topics)} topic(s) seen.")
    if args.md:
        with open(args.md, "w") as fh:
            fh.write(sv.markdown({"sn": sn, "ip": ip}, phases))
        print(f"markdown written to {args.md}")
    if args.json:
        with open(args.json, "w") as fh:
            json.dump({t: {**v, "phases": sorted(v["phases"])}
                       for t, v in sv.topics.items()}, fh, indent=2, default=str)
        print(f"raw survey written to {args.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
