/*
 * errors.js - the U1 fault catalogue.
 *
 * GENERATED by docs/u1-webui/tools/gen_error_module.py from
 * docs/u1-webui/data/error-catalog.json. Do not edit by hand.
 *
 * Codes are 16 hex digits: SSSS MMMM UUUU EEEE
 *   class/severity, subsystem, unit index (toolhead), specific fault.
 * See docs/u1-webui/06-errors/01-live-error-catalogue.md
 */
'use strict';

export const SUBSYSTEMS = {
 "0522": "system / motion",
 "0523": "toolhead",
 "0525": "filament",
 "0526": "heated bed",
 "0527": "chamber",
 "0528": "homing / axis",
 "0530": "calibration / detection",
 "0531": "job / storage",
 "0532": "defect detection (vision)",
 "0533": "top cover / chamber"
};

/** 442 codes, [title, description]. */
export const FAULTS = {
"0001052300000037": [
"Toolhead Maintenance",
"Toolhead swapping times have reached maintenance requirement. Clean the Pogopins on both sides, and add grease to the steel balls and steel pins of the toolhead."
],
"0001052300010048": [
"Toolhead Swapping Anomaly",
"A Pogo Pin connection error was detected during printing. Clean the contacts on the toolhead and toolhead swapper. If the error persists, tap to view the error count and contact support."
],
"0001052500000008": [
"Filament Anomaly",
"Toolhead 1 has residual filament. Unload the filament from the toolhead first, then retry."
],
"0001052500000010": [
"Filament Pre-loading Anomaly",
"Feeder 1 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001052500000011": [
"Filament Pre-loading Anomaly",
"Feeder 1 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0001052500000012": [
"Filament Pre-loading Anomaly",
"Feeder 1 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500000013": [
"Filament Pre-loading Anomaly",
"No filament detected in Feeder 1. Insert filament."
],
"0001052500000014": [
"Filament Pre-loading Anomaly",
"Feeder 1 feeding timeout. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500000015": [
"Filament Pre-loading Anomaly",
"Residual filament in Toolhead 1. Remove the residual filament from the toolhead, then reload."
],
"0001052500000090": [
"Manual Loading Anomaly",
"Feeder 1 manual loading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001052500010008": [
"Filament Anomaly",
"Toolhead 2 has residual filament. Unload the filament from the toolhead first, then retry."
],
"0001052500010010": [
"Filament Pre-loading Anomaly",
"Feeder 2 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001052500010011": [
"Filament Pre-loading Anomaly",
"Feeder 2 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0001052500010012": [
"Filament Pre-loading Anomaly",
"Feeder 2 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500010013": [
"Filament Pre-loading Anomaly",
"No filament detected in Feeder 2. Insert filament."
],
"0001052500010014": [
"Filament Pre-loading Anomaly",
"Feeder 2 feeding timeout. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500010015": [
"Filament Pre-loading Anomaly",
"Residual filament in Toolhead 2. Remove the residual filament from the toolhead, then reload."
],
"0001052500010090": [
"Manual Loading Anomaly",
"Feeder 2 manual loading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001052500020008": [
"Filament Anomaly",
"Toolhead 3 has residual filament. Unload the filament from the toolhead first, then retry."
],
"0001052500020010": [
"Filament Pre-loading Anomaly",
"Feeder 3 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001052500020011": [
"Filament Pre-loading Anomaly",
"Feeder 3 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0001052500020012": [
"Filament Pre-loading Anomaly",
"Feeder 3 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500020013": [
"Filament Pre-loading Anomaly",
"No filament detected in Feeder 3. Insert filament."
],
"0001052500020014": [
"Filament Pre-loading Anomaly",
"Feeder 3 feeding timeout. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500020015": [
"Filament Pre-loading Anomaly",
"Residual filament in Toolhead 3. Remove the residual filament from the toolhead, then reload."
],
"0001052500020090": [
"Manual Loading Anomaly",
"Feeder 3 manual loading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001052500030008": [
"Filament Anomaly",
"Toolhead 4 has residual filament. Unload the filament from the toolhead first, then retry."
],
"0001052500030010": [
"Filament Pre-loading Anomaly",
"Feeder 4 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001052500030011": [
"Filament Pre-loading Anomaly",
"Feeder 4 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0001052500030012": [
"Filament Pre-loading Anomaly",
"Feeder 4 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500030013": [
"Filament Pre-loading Anomaly",
"No filament detected in Feeder 4. Insert filament."
],
"0001052500030014": [
"Filament Pre-loading Anomaly",
"Feeder 4 feeding timeout. The filament may be tangled or the feeding path obstructed. Reload the filament after resolving the issue."
],
"0001052500030015": [
"Filament Pre-loading Anomaly",
"Residual filament in Toolhead 4. Remove the residual filament from the toolhead, then reload."
],
"0001052500030090": [
"Manual Loading Anomaly",
"Feeder 4 manual loading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0001053000000029": [
"Uneven Heated Bed Detected",
"The heated bed flatness deviation is too large. Please perform manual bed leveling."
],
"0001053100000000": [
"System Anomaly",
"Failed to retrieve file list."
],
"0001053100000001": [
"System Anomaly",
"Printer is printing, cannot operate slicing files. Retry when printer is idle."
],
"0001053100000002": [
"System Anomaly",
"Commands M28, M29, M30 are not supported. Please remove them."
],
"0001053100000003": [
"System Anomaly",
"Parsing G-code commands from slicing file. Resetting slicing file is not allowed."
],
"0001053100000004": [
"System Anomaly",
"Cannot open slicing file."
],
"0001053100000005": [
"System Anomaly",
"Failed to resume printing after power outage."
],
"0001053100000006": [
"System Anomaly",
"Deleting power-off data is not allowed during printing."
],
"0001053100000007": [
"System Anomaly",
"Cloud print file download failed. Check your network connection and retry. If issue persists, contact technical support."
],
"0001053100000008": [
"System Anomaly",
"USB flash drive read anomaly. Ensure the USB flash drive is properly connected and retry. If issue persists, contact technical support."
],
"0001053100000011": [
"Cloud Print File Verification Failed",
"Resend the print file."
],
"0001053100000012": [
"Cloud Print File Extraction Failed",
"Resend the print file."
],
"0001053100000015": [
"Modification Failed",
"Channel mapping cannot be modified while a print is in progress. Please make adjustments after the task is completed."
],
"0001053100000016": [
"Modification Failed",
"Preference settings cannot be modified while a print is in progress. Please make adjustments after the task is completed."
],
"0002052300000000": [
"Filament Anomaly",
"Filament runout detected in Toolhead 1. Try reloading filament, then tap the play button to resume the print job."
],
"0002052300000007": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000008": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000009": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000010": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000011": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000012": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000013": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000014": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000015": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000016": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000017": [
"Toolhead Swapping Failure",
"Toolhead 1 swapping failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300000018": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300000019": [
"Toolhead Parking Failure",
"Toolhead 1 parking failed. Retry. If the issue persists, contact technical support."
],
"0002052300000020": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300000021": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300000022": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300000023": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300000024": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000025": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000026": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000027": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000028": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000029": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000030": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000031": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000032": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000033": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000034": [
"Toolhead Picking Failure",
"Toolhead 1 picking failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300000035": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300000038": [
"Printing Anomaly",
"Check if the filament for Toolhead 1 is broken inside the tube, tangled on the spool, or if the toolhead is clogged. After troubleshooting, tap to resume printing. If issue persists, contact technical support."
],
"0002052300000039": [
"Filament Anomaly",
"Filament information not set for Toolhead 1. Go to the filament page to edit, then tap to resume printing."
],
"0002052300000040": [
"Toolhead Swapping Anomaly",
"Toolhead 1 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300000041": [
"Toolhead Swapping Anomaly",
"Toolhead 1 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300000042": [
"Toolhead Swapping Anomaly",
"Toolhead 1 return failed. Foreign objects may be present in the dock or working area. Remove any obstructions, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300000043": [
"Toolhead Swapping Anomaly",
"Toolhead 1 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300000044": [
"Toolhead Swapping Anomaly",
"Toolhead 1 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300000045": [
"Toolhead Swapping Anomaly",
"Toolhead 1 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300000046": [
"Toolhead Swapping Anomaly",
"Toolhead 1 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300000047": [
"Toolhead Swapping Anomaly",
"Toolhead 1 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300009000": [
"Flow Calibration Anomaly",
"Toolhead 1 flow calibration anomaly. Contact technical support."
],
"0002052300010000": [
"Filament Anomaly",
"Filament runout detected in Toolhead 2. Try reloading filament, then tap the play button to resume the print job."
],
"0002052300010007": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010008": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010009": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010010": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010011": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010012": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010013": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010014": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010015": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010016": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010017": [
"Toolhead Swapping Failure",
"Toolhead 2 swapping failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300010018": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300010019": [
"Toolhead Parking Failure",
"Toolhead 2 parking failed. Retry. If the issue persists, contact technical support."
],
"0002052300010020": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300010021": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300010022": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300010023": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300010024": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010025": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010026": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010027": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010028": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010029": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010030": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010031": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010032": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010033": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010034": [
"Toolhead Picking Failure",
"Toolhead 2 picking failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300010035": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300010038": [
"Printing Anomaly",
"Check if the filament for Toolhead 2 is broken inside the tube, tangled on the spool, or if the toolhead is clogged. After troubleshooting, tap to resume printing. If issue persists, contact technical support."
],
"0002052300010039": [
"Filament Anomaly",
"Filament information not set for Toolhead 2. Go to the filament page to edit, then tap to resume printing."
],
"0002052300010040": [
"Toolhead Swapping Anomaly",
"Toolhead 2 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300010041": [
"Toolhead Swapping Anomaly",
"Toolhead 2 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300010042": [
"Toolhead Swapping Anomaly",
"Toolhead 2 return failed. Foreign objects may be present in the dock or working area. Remove any obstructions, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300010043": [
"Toolhead Swapping Anomaly",
"Toolhead 2 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300010044": [
"Toolhead Swapping Anomaly",
"Toolhead 2 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300010045": [
"Toolhead Swapping Anomaly",
"Toolhead 2 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300010046": [
"Toolhead Swapping Anomaly",
"Toolhead 2 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300010047": [
"Toolhead Swapping Anomaly",
"Toolhead 2 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300019000": [
"Flow Calibration Anomaly",
"Toolhead 2 flow calibration anomaly. Contact technical support."
],
"0002052300020000": [
"Filament Anomaly",
"Filament runout detected in Toolhead 3. Try reloading filament, then tap the play button to resume the print job."
],
"0002052300020007": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020008": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020009": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020010": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020011": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020012": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020013": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020014": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020015": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020016": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020017": [
"Toolhead Swapping Failure",
"Toolhead 3 swapping failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300020018": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300020019": [
"Toolhead Parking Failure",
"Toolhead 3 parking failed. Retry. If the issue persists, contact technical support."
],
"0002052300020020": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300020021": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300020022": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300020023": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300020024": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020025": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020026": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020027": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020028": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020029": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020030": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020031": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020032": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020033": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020034": [
"Toolhead Picking Failure",
"Toolhead 3 picking failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300020035": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300020038": [
"Printing Anomaly",
"Check if the filament for Toolhead 3 is broken inside the tube, tangled on the spool, or if the toolhead is clogged. After troubleshooting, tap to resume printing. If issue persists, contact technical support."
],
"0002052300020039": [
"Filament Anomaly",
"Filament information not set for Toolhead 3. Go to the filament page to edit, then tap to resume printing."
],
"0002052300020040": [
"Toolhead Swapping Anomaly",
"Toolhead 3 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300020041": [
"Toolhead Swapping Anomaly",
"Toolhead 3 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300020042": [
"Toolhead Swapping Anomaly",
"Toolhead 3 return failed. Foreign objects may be present in the dock or working area. Remove any obstructions, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300020043": [
"Toolhead Swapping Anomaly",
"Toolhead 3 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300020044": [
"Toolhead Swapping Anomaly",
"Toolhead 3 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300020045": [
"Toolhead Swapping Anomaly",
"Toolhead 3 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300020046": [
"Toolhead Swapping Anomaly",
"Toolhead 3 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300020047": [
"Toolhead Swapping Anomaly",
"Toolhead 3 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300029000": [
"Flow Calibration Anomaly",
"Toolhead 3 flow calibration anomaly. Contact technical support."
],
"0002052300030000": [
"Filament Anomaly",
"Filament runout detected in Toolhead 4. Try reloading filament, then tap the play button to resume the print job."
],
"0002052300030007": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030008": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030009": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030010": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030011": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030012": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030013": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030014": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030015": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030016": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030017": [
"Toolhead Swapping Failure",
"Toolhead 4 swapping failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If the anomaly persists, contact technical support."
],
"0002052300030018": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300030019": [
"Toolhead Parking Failure",
"Toolhead 4 parking failed. Retry. If the issue persists, contact technical support."
],
"0002052300030020": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300030021": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300030022": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Retry. If issue persists, contact technical support."
],
"0002052300030023": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300030024": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 1 and Toolhead 2 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030025": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 1 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030026": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 1 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030027": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030028": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030029": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030030": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 3 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030031": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 1, Toolhead 2 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030032": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 1, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030033": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check if Toolhead 2, Toolhead 3 and Toolhead 4 are dropped or tilted, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030034": [
"Toolhead Picking Failure",
"Toolhead 4 picking failed. Check all toolheads one by one for dropping or tilting, adjust manually and retry. If anomaly persists, contact technical support."
],
"0002052300030035": [
"Toolhead Swapping Anomaly",
"Check if the current toolhead is properly picked and placed, and ensure all idle toolheads on the dock are securely installed. Reinstall any misaligned toolheads, then tap to resume the task."
],
"0002052300030038": [
"Printing Anomaly",
"Check if the filament for Toolhead 4 is broken inside the tube, tangled on the spool, or if the toolhead is clogged. After troubleshooting, tap to resume printing. If issue persists, contact technical support."
],
"0002052300030039": [
"Filament Anomaly",
"Filament information not set for Toolhead 4. Go to the filament page to edit, then tap to resume printing."
],
"0002052300030040": [
"Toolhead Swapping Anomaly",
"Toolhead 4 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300030041": [
"Toolhead Swapping Anomaly",
"Toolhead 4 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300030042": [
"Toolhead Swapping Anomaly",
"Toolhead 4 return failed. Foreign objects may be present in the dock or working area. Remove any obstructions, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300030043": [
"Toolhead Swapping Anomaly",
"Toolhead 4 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300030044": [
"Toolhead Swapping Anomaly",
"Toolhead 4 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300030045": [
"Toolhead Swapping Anomaly",
"Toolhead 4 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300030046": [
"Toolhead Swapping Anomaly",
"Toolhead 4 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300030047": [
"Toolhead Swapping Anomaly",
"Toolhead 4 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052300039000": [
"Flow Calibration Anomaly",
"Toolhead 4 flow calibration anomaly. Contact technical support."
],
"0002052500000000": [
"Filament Anomaly",
"Toolhead 1 filament feeder anomaly. Contact technical support."
],
"0002052500000001": [
"Filament Anomaly",
"Toolhead 1 filament feeder anomaly. Contact technical support."
],
"0002052500000002": [
"Filament Anomaly",
"Filament Feeder 1 Loading Anomaly. Check for filament tangles or loose connector connections. If printing is in progress, tap the play button to resume the print job after troubleshooting."
],
"0002052500000003": [
"Filament Not Loaded",
"Toolhead 1 filament feeder detected no filament entry. Insert filament."
],
"0002052500000004": [
"Extrusion Blockage",
"Filament extrusion blocked at the drive gear of Toolhead 1. Check and clean, then retry. If printer is printing, tap the play button to the play button the print job."
],
"0002052500000005": [
"Filament Anomaly",
"Toolhead 1 filament feeder loading timed out. Check if the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to the play button the print job."
],
"0002052500000006": [
"Filament Anomaly",
"Toolhead 1 filament feeder loading timed out. Check if the filament tube is detached or the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to resume the print job."
],
"0002052500000030": [
"Filament Loading Anomaly",
"Feeder 1 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500000031": [
"Filament Loading Anomaly",
"Feeder 1 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0002052500000032": [
"Filament Loading Anomaly",
"Feeder 1 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500000033": [
"Filament Loading Anomaly",
"No filament detected in Feeder 1. Insert filament."
],
"0002052500000034": [
"Filament Loading Anomaly",
"Feeder 1 feeding timeout. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500000035": [
"Filament Loading Anomaly",
"Feeder 1 feeding stroke overrun. Check if the filament tube has detached from this feeder. After reconnecting, tap to resume, or reload the filament."
],
"0002052500000050": [
"Extrusion Anomaly",
"Feeder 1 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500000051": [
"Extrusion Anomaly",
"Feeder 1 Feeding Failure. The filament may be tangled, jammed in the extrusion gears, or the nozzle may be clogged. Troubleshoot and retry."
],
"0002052500000070": [
"Filament Unloading Anomaly",
"Feeder 1 unloading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500010000": [
"Filament Anomaly",
"Toolhead 2 filament feeder anomaly. Contact technical support."
],
"0002052500010001": [
"Filament Anomaly",
"Toolhead 2 filament feeder anomaly. Contact technical support."
],
"0002052500010002": [
"Filament Anomaly",
"Filament Feeder 2 Loading Anomaly. Check for filament tangles or loose connector connections. If printing is in progress, tap the play button to resume the print job after troubleshooting."
],
"0002052500010003": [
"Filament Not Loaded",
"Toolhead 2 filament feeder detected no filament entry. Insert filament."
],
"0002052500010004": [
"Extrusion Blockage",
"Filament extrusion blocked at the drive gear of Toolhead 2. Check and clean, then retry. If printer is printing, tap the play button to the play button the print job."
],
"0002052500010005": [
"Filament Anomaly",
"Toolhead 2 filament feeder loading timed out. Check if the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to resume the print job."
],
"0002052500010006": [
"Filament Anomaly",
"Toolhead 2 filament feeder loading timed out. Check if the filament tube is detached or the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to resume the print job."
],
"0002052500010030": [
"Filament Loading Anomaly",
"Feeder 2 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500010031": [
"Filament Loading Anomaly",
"Feeder 2 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0002052500010032": [
"Filament Loading Anomaly",
"Feeder 2 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500010033": [
"Filament Loading Anomaly",
"No filament detected in Feeder 2. Insert filament."
],
"0002052500010034": [
"Filament Loading Anomaly",
"Feeder 2 feeding timeout. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500010035": [
"Filament Loading Anomaly",
"Feeder 2 feeding stroke overrun. Check if the filament tube has detached from this feeder. After reconnecting, tap to resume, or reload the filament."
],
"0002052500010050": [
"Extrusion Anomaly",
"Feeder 2 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500010051": [
"Extrusion Anomaly",
"Feeder 2 Feeding Failure. The filament may be tangled, jammed in the extrusion gears, or the nozzle may be clogged. Troubleshoot and retry."
],
"0002052500010070": [
"Filament Unloading Anomaly",
"Feeder 2 unloading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500020000": [
"Filament Anomaly",
"Toolhead 3 filament feeder anomaly. Contact technical support."
],
"0002052500020001": [
"Filament Anomaly",
"Toolhead 3 filament feeder anomaly. Contact technical support."
],
"0002052500020002": [
"Filament Anomaly",
"Filament Feeder 3 Loading Anomaly. Check for filament tangles or loose connector connections. If printing is in progress, tap the play button to resume the print job after troubleshooting."
],
"0002052500020003": [
"Filament Not Loaded",
"Toolhead 3 filament feeder detected no filament entry. Insert filament."
],
"0002052500020004": [
"Extrusion Blockage",
"Filament extrusion blocked at the drive gear of Toolhead 3. Check and clean, then retry. If printer is printing, tap the play button to the play button the print job."
],
"0002052500020005": [
"Filament Anomaly",
"Toolhead 3 filament feeder loading timed out. Check if the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to resume the print job."
],
"0002052500020006": [
"Filament Anomaly",
"Toolhead 3 filament feeder loading timed out. Check if the filament tube is detached or the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to resume the print job."
],
"0002052500020030": [
"Filament Loading Anomaly",
"Feeder 3 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500020031": [
"Filament Loading Anomaly",
"Feeder 3 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0002052500020032": [
"Filament Loading Anomaly",
"Feeder 3 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500020033": [
"Filament Loading Anomaly",
"No filament detected in Feeder 3. Insert filament."
],
"0002052500020034": [
"Filament Loading Anomaly",
"Feeder 3 feeding timeout. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500020035": [
"Filament Loading Anomaly",
"Feeder 3 feeding stroke overrun. Check if the filament tube has detached from this feeder. After reconnecting, tap to resume, or reload the filament."
],
"0002052500020050": [
"Extrusion Anomaly",
"Feeder 3 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500020051": [
"Extrusion Anomaly",
"Feeder 3 Feeding Failure. The filament may be tangled, jammed in the extrusion gears, or the nozzle may be clogged. Troubleshoot and retry."
],
"0002052500020070": [
"Filament Unloading Anomaly",
"Feeder 3 unloading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500030000": [
"Filament Anomaly",
"Toolhead 4 filament feeder anomaly. Contact technical support."
],
"0002052500030001": [
"Filament Anomaly",
"Toolhead 4 filament feeder anomaly. Contact technical support."
],
"0002052500030002": [
"Filament Anomaly",
"Filament Feeder 4 Loading Anomaly. Check for filament tangles or loose connector connections. If printing is in progress, tap the play button to resume the print job after troubleshooting."
],
"0002052500030003": [
"Filament Not Loaded",
"Toolhead 4 filament feeder detected no filament entry. Insert filament."
],
"0002052500030004": [
"Extrusion Blockage",
"Filament extrusion blocked at the drive gear of Toolhead 4. Check and clean, then retry. If printer is printing, tap the play button to the play button the print job."
],
"0002052500030005": [
"Filament Anomaly",
"Toolhead 4 filament feeder loading timed out. Check if the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to resume the print job."
],
"0002052500030006": [
"Filament Anomaly",
"Toolhead 4 filament feeder loading timed out. Check if the filament tube is detached or the loading path is blocked, ensure it is clear, then retry. If printer is printing, tap the play button to resume the print job."
],
"0002052500030030": [
"Filament Loading Anomaly",
"Feeder 4 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500030031": [
"Filament Loading Anomaly",
"Feeder 4 motor speed anomaly. Check and ensure the feeder cable is properly connected. If the error persists, contact Technical Support."
],
"0002052500030032": [
"Filament Loading Anomaly",
"Feeder 4 encoder wheel speed anomaly. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500030033": [
"Filament Loading Anomaly",
"No filament detected in Feeder 4. Insert filament."
],
"0002052500030034": [
"Filament Loading Anomaly",
"Feeder 4 feeding timeout. The filament may be tangled or the feeding path obstructed. Tap to resume, or reload the filament after resolving the issue."
],
"0002052500030035": [
"Filament Loading Anomaly",
"Feeder 4 feeding stroke overrun. Check if the filament tube has detached from this feeder. After reconnecting, tap to resume, or reload the filament."
],
"0002052500030050": [
"Extrusion Anomaly",
"Feeder 4 anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052500030051": [
"Extrusion Anomaly",
"Feeder 4 Feeding Failure. The filament may be tangled, jammed in the extrusion gears, or the nozzle may be clogged. Troubleshoot and retry."
],
"0002052500030070": [
"Filament Unloading Anomaly",
"Feeder 4 unloading anomaly. Tap the error code for details. It is recommended to contact Technical Support for assistance."
],
"0002052800000000": [
"Homing Anomaly",
"Home X and Y axes first, then home Z axis."
],
"0002052800000001": [
"Homing Anomaly",
"Current toolhead is unavailable, cannot home. Restart printer and retry. If issue persists, contact technical support."
],
"0002052800000010": [
"Homing Anomaly",
"Home X and Y axes first before performing this operation."
],
"0002052800000011": [
"Homing Anomaly",
"Check if timing belts are tensioned properly, X and Y axes move smoothly, and there are no obstructions at the X and Y homing positions. Retry after troubleshooting. If issue persists, contact technical support."
],
"0002052800000012": [
"Homing Anomaly",
"Check if timing belts are tensioned properly, X and Y axes move smoothly, and there are no obstructions at the X and Y homing positions. Retry after troubleshooting. If issue persists, contact technical support."
],
"0002052800000013": [
"Homing Anomaly",
"Toolhead 1 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052800000014": [
"Homing Anomaly",
"Toolhead 1 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052800010013": [
"Homing Anomaly",
"Toolhead 2 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052800010014": [
"Homing Anomaly",
"Toolhead 2 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052800020013": [
"Homing Anomaly",
"Toolhead 3 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052800020014": [
"Homing Anomaly",
"Toolhead 3 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052800030013": [
"Homing Anomaly",
"Toolhead 4 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002052800030014": [
"Homing Anomaly",
"Toolhead 4 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0002053100000009": [
"Storage Space Low",
"Low device storage may affect printing functionality. Delete some G-code or timelapse files to free up space."
],
"0002053200000000": [
"System Anomaly",
"See anomaly details. Contact technical support."
],
"0002053200000001": [
"Possible Foreign Object Detected on Print Bed",
"Please check and remove any foreign objects. If none are found, click Continue to resume printing."
],
"0002053200000002": [
"Possible Spaghetti Defect Detected",
"Please inspect the model. If any defects are acceptable\u2014or none are found\u2014click Continue to resume printing."
],
"0002053200000003": [
"Possible Residue Detected on Print Bed",
"Please check and remove any residue. If none are found, click Continue to resume printing."
],
"0002053300000000": [
"Top Cover Anomaly",
"Internal circulation fan speed is abnormal. Please check for debris or a loose connector."
],
"0002053300000001": [
"Chamber Temperature Anomaly",
"The chamber is overheating. Please open the magnetic front door and the glass door to cool it down."
],
"0003052200000000": [
"System Anomaly",
"See anomaly details. Contact technical support."
],
"0003052200000001": [
"System Anomaly",
"Contact technical support."
],
"0003052200000002": [
"System Anomaly",
"Printer stopped. See anomaly details. Contact technical support."
],
"0003052200000003": [
"System Failed to Start",
"Configuration load anomaly. Contact technical support or restore factory settings."
],
"0003052200000004": [
"System Failed to Start",
"Configuration load anomaly. Contact technical support or restore factory settings."
],
"0003052200000005": [
"System Failed to Start",
"Communication protocol load anomaly. Contact technical support or update firmware."
],
"0003052200000006": [
"System Failed to Start",
"Host MCU connection failed. Contact technical support."
],
"0003052200000007": [
"System Failed to Start",
"Abnormal MCU connection. Contact technical support."
],
"0003052200000008": [
"System Anomaly",
"Host MCU connection interrupted. Contact technical support."
],
"0003052200000009": [
"Sensor Anomaly",
"Accelerometer storage anomaly. Try powering off and restarting to resume. If the problem recurs, contact technical support."
],
"0003052200000010": [
"Sensor Anomaly",
"Accelerometer failed to obtain valid device ID. Try powering off and restarting to resume. If the problem recurs, contact technical support."
],
"0003052200000011": [
"Motor Driver Anomaly",
"Motor driver anomaly. See anomaly details. Contact technical support."
],
"0003052200000012": [
"Axis Movement Anomaly",
"Tap Home first, then move the X axis."
],
"0003052200000013": [
"Axis Movement Anomaly",
"X-axis movement exceeded travel limit."
],
"0003052200000014": [
"Sensor Anomaly",
"ADC sensor configuration exceeded limit. System has shut down for protection. Export printer logs and contact technical support."
],
"0003052200000015": [
"Temperature Anomaly",
"Heating module failed to heat up normally. System has shut down for protection. Export printer logs and contact technical support."
],
"0003052200000016": [
"System Anomaly",
"Host MCU control timed out. System has shut down for protection. Contact technical support."
],
"0003052200000017": [
"System Anomaly",
"Mainboard MCU detected power-off signal. System has shut down for protection. Contact technical support."
],
"0003052200010006": [
"System Failed to Start",
"Mainboard MCU connection failed. Contact technical support."
],
"0003052200010008": [
"System Anomaly",
"Mainboard MCU connection interrupted. Contact technical support."
],
"0003052200010012": [
"Axis Movement Anomaly",
"Tap Home first, then move the Y axis."
],
"0003052200010013": [
"Axis Movement Anomaly",
"Y-axis movement exceeded travel limit."
],
"0003052200010016": [
"System Anomaly",
"Mainboard MCU control timed out. System has shut down for protection. Contact technical support."
],
"0003052200010017": [
"System Anomaly",
"Toolhead 1 MCU detected power-off signal. System has shut down for protection. Contact technical support."
],
"0003052200020006": [
"System Failed to Start",
"Toolhead 1 MCU connection failed. Power off printer, check toolhead cable, then restart printer. If issue persists, contact technical support."
],
"0003052200020008": [
"System Anomaly",
"Toolhead 1 MCU connection interrupted. Power off printer, check Toolhead 1 cable, then restart to resume operation."
],
"0003052200020012": [
"Axis Movement Anomaly",
"Tap Home first, then move the Z axis."
],
"0003052200020013": [
"Axis Movement Anomaly",
"Z-axis movement exceeded travel limit."
],
"0003052200020016": [
"System Anomaly",
"Toolhead 1 MCU control timed out. System has shut down for protection. Power off printer, check Toolhead 1 cable, then restart to resume operation."
],
"0003052200020017": [
"System Anomaly",
"Toolhead 2 MCU detected power-off signal. System has shut down for protection. Contact technical support."
],
"0003052200030006": [
"System Failed to Start",
"Toolhead 2 MCU connection failed. Power off printer, check toolhead cable, then restart printer. If issue persists, contact technical support."
],
"0003052200030008": [
"System Anomaly",
"Toolhead 2 MCU connection interrupted. Power off printer, check Toolhead 2 cable, then restart to resume operation."
],
"0003052200030016": [
"System Anomaly",
"Toolhead 2 MCU control timed out. System has shut down for protection. Power off printer, check Toolhead 2 cable, then restart to resume operation."
],
"0003052200030017": [
"System Anomaly",
"Toolhead 3 MCU detected power-off signal. System has shut down for protection. Contact technical support."
],
"0003052200040006": [
"System Failed to Start",
"Toolhead 3 MCU connection failed. Power off printer, check toolhead cable, then restart printer. If issue persists, contact technical support."
],
"0003052200040008": [
"System Anomaly",
"Toolhead 3 MCU connection interrupted. Power off printer, check Toolhead 3 cable, then restart to resume operation."
],
"0003052200040016": [
"System Anomaly",
"Toolhead 3 MCU control timed out. System has shut down for protection. Power off printer, check Toolhead 3 cable, then restart to resume operation."
],
"0003052200040017": [
"System Anomaly",
"Toolhead 4 MCU detected power-off signal. System has shut down for protection. Contact technical support."
],
"0003052200050006": [
"System Failed to Start",
"Toolhead 4 MCU connection failed. Power off printer, check toolhead cable, then restart printer. If issue persists, contact technical support."
],
"0003052200050008": [
"System Anomaly",
"Toolhead 4 MCU connection interrupted. Power off printer, check Toolhead 4 cable, then restart to resume operation."
],
"0003052200050016": [
"System Anomaly",
"Toolhead 4 MCU control timed out. System has shut down for protection. Power off printer, check Toolhead 4 cable, then restart to resume operation."
],
"0003052201000006": [
"System Failed to Start",
"No toolhead detected. Please contact Technical Support."
],
"0003052300000001": [
"Nozzle Temperature Anomaly",
"Toolhead 1 nozzle temperature insufficient. Nozzle extrusion temperature must be above 170\u00b0C."
],
"0003052300000002": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 1 thermistor."
],
"0003052300000003": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 1 ceramic heater or thermistor."
],
"0003052300000004": [
"Extrusion Length Exceeded",
"Toolhead 1 single extrusion distance was too long. There may be incorrect codes in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300000005": [
"Extrusion Flow Exceeded",
"Toolhead 1 printing extrusion volume exceeded maximum allowed. There may be incorrect configurations in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300000006": [
"Nozzle Temperature Anomaly",
"The G-code file may have set a toolhead unrecognized by printer. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300000036": [
"Nozzle Temperature Out of Range",
"Nozzle temperature set for Toolhead 1 is outside the allowable range. Reset to valid parameters."
],
"0003052300009001": [
"Flow Calibration Unavailable",
"Filament used in Toolhead 1 is prone to clogging Nozzle and does not meet the calibration requirements."
],
"0003052300010001": [
"Nozzle Temperature Anomaly",
"Toolhead 2 nozzle temperature insufficient. Nozzle extrusion temperature must be above 170\u00b0C."
],
"0003052300010002": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 2 thermistor."
],
"0003052300010003": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 2 ceramic heater or thermistor."
],
"0003052300010004": [
"Extrusion Length Exceeded",
"Toolhead 2 single extrusion distance was too long. There may be incorrect codes in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300010005": [
"Extrusion Flow Exceeded",
"Toolhead 2 printing extrusion volume exceeded maximum allowed. There may be incorrect configurations in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300010036": [
"Nozzle Temperature Out of Range",
"Nozzle temperature set for Toolhead 2 is outside the allowable range. Reset to valid parameters."
],
"0003052300019001": [
"Flow Calibration Unavailable",
"Filament used in Toolhead 2 is prone to clogging Nozzle and does not meet the calibration requirements."
],
"0003052300020001": [
"Nozzle Temperature Anomaly",
"Toolhead 3 nozzle temperature insufficient. Nozzle extrusion temperature must be above 170\u00b0C."
],
"0003052300020002": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 3 thermistor."
],
"0003052300020003": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 3 ceramic heater or thermistor."
],
"0003052300020004": [
"Extrusion Length Exceeded",
"Toolhead 3 single extrusion distance was too long. There may be incorrect codes in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300020005": [
"Extrusion Flow Exceeded",
"Toolhead 3 printing extrusion volume exceeded maximum allowed. There may be incorrect configurations in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300020036": [
"Nozzle Temperature Out of Range",
"Nozzle temperature set for Toolhead 3 is outside the allowable range. Reset to valid parameters."
],
"0003052300029001": [
"Flow Calibration Unavailable",
"Filament used in Toolhead 3 is prone to clogging Nozzle and does not meet the calibration requirements."
],
"0003052300030001": [
"Nozzle Temperature Anomaly",
"Toolhead 4 nozzle temperature insufficient. Nozzle extrusion temperature must be above 170\u00b0C."
],
"0003052300030002": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 4 thermistor."
],
"0003052300030003": [
"Nozzle Temperature Anomaly",
"Power off printer, then check the connection of Toolhead 4 ceramic heater or thermistor."
],
"0003052300030004": [
"Extrusion Length Exceeded",
"Toolhead 4 single extrusion distance was too long. There may be incorrect codes in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300030005": [
"Extrusion Flow Exceeded",
"Toolhead 4 printing extrusion volume exceeded maximum allowed. There may be incorrect configurations in the G-code file. It is recommended to use G-code files exported by Snapmaker Orca for printing to avoid this issue."
],
"0003052300030036": [
"Nozzle Temperature Out of Range",
"Nozzle temperature set for Toolhead 4 is outside the allowable range. Reset to valid parameters."
],
"0003052300039001": [
"Flow Calibration Unavailable",
"Filament used in Toolhead 4 is prone to clogging Nozzle and does not meet the calibration requirements."
],
"0003052600000000": [
"Heated Bed Temperature Abnormal",
"Possible temperature sensor failure. Contact Technical Support."
],
"0003052600000001": [
"Heated Bed Temperature Abnormal",
"Heated bed heating anomaly. Contact technical support."
],
"0003052700000000": [
"Chamber Temperature Abnormal",
"Check and ensure the temperature sensor cable is properly connected, or contact Technical Support."
],
"0003052800000002": [
"Axis Movement Anomaly",
"X-axis movement anomaly. Retry. If anomaly occurs repeatedly, contact technical support."
],
"0003052800000003": [
"Axis Movement Anomaly",
"X-axis movement anomaly. Retry. If anomaly occurs repeatedly, contact technical support."
],
"0003052800000004": [
"Axis Movement Anomaly",
"Check if X-axis movement has obvious resistance, then retry. If issue persists, contact technical support."
],
"0003052800000005": [
"Axis Movement Anomaly",
"Check if moving axes have obvious resistance, then retry. If issue persists, contact technical support."
],
"0003052800000006": [
"Axis Movement Anomaly",
"Check if timing belts are tensioned properly, X and Y axes move smoothly, and there are no obstructions at the X and Y homing positions. Retry after troubleshooting. If issue persists, contact technical support."
],
"0003052800000007": [
"System Anomaly",
"System is in shutdown protection, cannot home. Restart printer and retry. If the problem persists, contact technical support."
],
"0003052800000008": [
"System Anomaly",
"System is in shutdown protection, cannot level. Restart printer and retry. If the problem persists, contact technical support."
],
"0003052800000009": [
"Sensor Anomaly",
"Failed to activate. Retry. If anomaly occurs repeatedly, contact technical support."
],
"0003052800010002": [
"Axis Movement Anomaly",
"Y-axis movement anomaly. Retry. If anomaly occurs repeatedly, contact technical support."
],
"0003052800010003": [
"Axis Movement Anomaly",
"Y-axis movement anomaly. Retry. If anomaly occurs repeatedly, contact technical support."
],
"0003052800010004": [
"Axis Movement Anomaly",
"Check if Y-axis movement has obvious resistance, then retry. If issue persists, contact technical support."
],
"0003052800020002": [
"Axis Movement Anomaly",
"Z-axis movement anomaly. Retry. If anomaly occurs repeatedly, contact technical support."
],
"0003052800020003": [
"Axis Movement Anomaly",
"Z-axis movement anomaly. Retry. If anomaly occurs repeatedly, contact technical support."
],
"0003052800020004": [
"Axis Movement Anomaly",
"Check if Z-axis movement has obvious resistance, then retry. If issue persists, contact technical support."
],
"0003052800030002": [
"Homing Anomaly",
"Retry. If issue persists, contact technical support."
],
"0003052800030003": [
"Homing Anomaly",
"Retry. If issue persists, contact technical support."
],
"0003052800030004": [
"Homing Anomaly",
"Homing sensor not triggered. Check the nozzle for residual filament and clean it before retrying. If issue persists, contact technical support."
],
"0003053000000000": [
"Calibration Anomaly",
"Toolhead 1 calibration sensor anomaly. Check if the calibration sensor is disconnected. For assistance, contact technical support."
],
"0003053000000001": [
"Calibration Anomaly",
"Toolhead 1 calibration sensor anomaly. Sensor data exceeded allowable range. Contact technical support."
],
"0003053000000002": [
"Calibration Anomaly",
"Toolhead must be homed before calibration module works. Home and retry. If issue persists, contact technical support."
],
"0003053000000003": [
"Calibration Anomaly",
"Incorrect calibration parameters. Contact technical support."
],
"0003053000000004": [
"Calibration Anomaly",
"Calibration failed. Check if toolhead is properly positioned, manually return to home position, then retry. If issue persists, contact technical support."
],
"0003053000000005": [
"Calibration Anomaly",
"Incorrect operation command. Check if toolheads match placement position numbers, ensure numbers match, then retry. If issue persists, contact technical support."
],
"0003053000000006": [
"Calibration Anomaly",
"Calibration module model of current toolhead does not match. Contact technical support."
],
"0003053000000007": [
"Calibration Anomaly",
"Probe command anomaly. Axes other than X, Y, Z are used. Use correct commands."
],
"0003053000000008": [
"Calibration Anomaly",
"Check the X axis for any obstructions and if toolhead nozzle has residual material. Clean and retry. If issue persists, contact technical support."
],
"0003053000000009": [
"Calibration Anomaly",
"Calibration unavailable due to system anomaly. Contact technical support."
],
"0003053000000010": [
"Heated Bed Detection Anomaly",
"PEI sheet detected as removed. Place PEI sheet and retry printing."
],
"0003053000000011": [
"Heated Bed Detection Anomaly",
"PEI sheet detected as not removed. Remove PEI sheet and retry calibration."
],
"0003053000000012": [
"Heated Bed Detection Anomaly",
"Heated bed detection anomaly. Contact technical support."
],
"0003053000000013": [
"Detection Anomaly",
"Attach any one toolhead and retry."
],
"0003053000000014": [
"Detection Anomaly",
"Toolhead 1 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000000015": [
"Detection Anomaly",
"Toolhead 1 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000000016": [
"Detection Anomaly",
"Toolhead 1 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000000017": [
"Heated Bed Detection Anomaly",
"The PEI sheet is not properly positioned. Correctly place the PEI sheet and retry."
],
"0003053000000018": [
"Calibration Anomaly",
"Toolhead XYZ offset calibration value exceeds the maximum allowed range."
],
"0003053000000019": [
"Calibration Failed",
"Toolhead Attach/Detach Coordinate Adjustment is not supported by the current printer profile."
],
"0003053000000020": [
"Calibration Failed",
"One or more toolheads are not securely seated on the dock. Ensure all toolheads are properly installed and try again."
],
"0003053000000021": [
"Toolhead Attach Verification Failed",
""
],
"0003053000000022": [
"Toolhead Detach Verification Failed",
""
],
"0003053000000024": [
"Homing Calibration Failed",
"Diagonal probing error."
],
"0003053000000025": [
"Homing Calibration Failed",
"Failed to verify the probe point."
],
"0003053000000026": [
"Homing Calibration Failed",
"Reached max retries."
],
"0003053000000027": [
"Homing Calibration Failed",
"Please retension the timing belt and try again. If the issue persists, perform a homing calibration."
],
"0003053000000028": [
"Homing Calibration Failed",
"Please retension the timing belt and try again. If the issue persists, perform a homing calibration."
],
"0003053000010000": [
"Calibration Anomaly",
"Toolhead 2 calibration sensor anomaly. Check if the calibration sensor is disconnected. For assistance, contact technical support."
],
"0003053000010001": [
"Calibration Anomaly",
"Toolhead 2 calibration sensor anomaly. Sensor data exceeded allowable range. Contact technical support."
],
"0003053000010008": [
"Calibration Anomaly",
"Check the Y axis for any obstructions and if toolhead nozzle has residual material. Clean and retry. If issue persists, contact technical support."
],
"0003053000010014": [
"Detection Anomaly",
"Toolhead 2 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000010015": [
"Detection Anomaly",
"Toolhead 2 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000010016": [
"Detection Anomaly",
"Toolhead 2 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000010021": [
"Toolhead Attach Verification Failed",
""
],
"0003053000010022": [
"Toolhead Detach Verification Failed",
""
],
"0003053000020000": [
"Calibration Anomaly",
"Toolhead 3 calibration sensor anomaly. Check if the calibration sensor is disconnected. For assistance, contact technical support."
],
"0003053000020001": [
"Calibration Anomaly",
"Toolhead 3 calibration sensor anomaly. Sensor data exceeded allowable range. Contact technical support."
],
"0003053000020008": [
"Calibration Anomaly",
"Check if Z axis for any obstructions and if toolhead nozzle has residual material. Clean and retry. If issue persists, contact technical support."
],
"0003053000020014": [
"Detection Anomaly",
"Toolhead 3 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000020015": [
"Detection Anomaly",
"Toolhead 3 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000020016": [
"Detection Anomaly",
"Toolhead 3 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000020021": [
"Toolhead Attach Verification Failed",
""
],
"0003053000020022": [
"Toolhead Detach Verification Failed",
""
],
"0003053000030000": [
"Calibration Anomaly",
"Toolhead 4 calibration sensor anomaly. Check if the calibration sensor is disconnected. For assistance, contact technical support."
],
"0003053000030001": [
"Calibration Anomaly",
"Toolhead 4 calibration sensor anomaly. Sensor data exceeded allowable range. Contact technical support."
],
"0003053000030014": [
"Detection Anomaly",
"Toolhead 4 detached. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000030015": [
"Detection Anomaly",
"Toolhead 4 Pogopin contact anomaly. Clean both the toolhead and the Pogopin contacts on the toolhead swapper using a dust-free cloth. Then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000030016": [
"Detection Anomaly",
"Toolhead 4 placement anomaly. Manually reinstall the toolhead into its dock, then tap to attempt resuming the job. If the error persists, contact Technical Support."
],
"0003053000030017": [
"Heated Bed Detection Anomaly",
"The PEI sheet is not properly positioned. Correctly place the PEI sheet and retry."
],
"0003053000030021": [
"Toolhead Attach Verification Failed",
""
],
"0003053000030022": [
"Toolhead Detach Verification Failed",
""
],
"0003053100000010": [
"Unrecognized G-code Commands",
"The print file contains G-code commands that are not supported by this device. Printing has been terminated."
],
"0003053100000014": [
"Print Start Failed",
"The nozzle diameter in the print file does not match the nozzle diameter of the target toolhead. Verify the slicer settings or replace the nozzle with a matching one, then try again."
],
"0003053100000018": [
"Print Start Failed",
"Filament does not meet the calibration requirements for the nozzle diameter corresponding to nozzle."
]
};

/** Decode a 16-hex-digit code into its four groups. */
export function decodeErrorCode(code) {
  const c = String(code == null ? '' : code).trim();
  if (!/^[0-9A-Fa-f]{16}$/.test(c)) return null;
  const subsystem = c.slice(4, 8);
  const unit = parseInt(c.slice(8, 12), 16);
  return {
    code: c.toUpperCase(),
    errorClass: c.slice(0, 4),
    subsystem,
    subsystemName: SUBSYSTEMS[subsystem] || 'unknown',
    unitIndex: unit,
    specific: c.slice(12, 16),
    // toolhead and filament faults number their head from the unit group
    toolhead: (subsystem === '0523' || subsystem === '0525') ? unit + 1 : null,
  };
}

/**
 * Look a fault up. Accepts the 16-digit form, and also a bare integer
 * `action_code`, which the state model reports as a number.
 */
export function lookupFault(code) {
  if (code == null || code === 0 || code === '') return null;
  let key = String(code).trim();
  if (/^[0-9]+$/.test(key) && key.length < 16) {
    key = Number(key).toString(16).toUpperCase().padStart(16, '0');
  }
  key = key.toUpperCase();
  const hit = FAULTS[key] || FAULTS[key.toLowerCase()];
  const parts = decodeErrorCode(key);
  if (!hit && !parts) return null;
  return {
    code: key,
    title: (hit && hit[0]) || 'Printer fault',
    description: (hit && hit[1]) || 'No description for this code in the shipped catalogue.',
    known: !!hit,
    ...(parts || {}),
  };
}
