name: Build Platform Compatibility

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      arch:
        required: false
        type: string
      build-deps-only:
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ inputs.os }}
    uses: ./.github/workflows/build_platform.yml
    with:
      platform: ${{ inputs.os == 'ubuntu-24.04' && 'linux' || inputs.os == 'windows-2022' && 'windows' || inputs.os == 'macos-14' && 'macos' || '' }}
      source_ref: ${{ github.sha }}
      version_label: ''
      tests_passed: false
      sign_artifacts: false
      package_artifact: ${{ !inputs.build-deps-only }}
